config/config.default.js
lib/egg.js
test/fixtures/apps/app-start-timeout/app.js
test/fixtures/apps/app-start-timeout/config/config.default.js
test/fixtures/apps/app-start-timeout/package.json
test/lib/application.test.js

emit startTimeout event if app don't ready after `config.workerStartTimeout` ms.

feat(application): emit startTimeout event

---

app/extend/context.js
lib/egg.js
package.json
test/app/extend/application.test.js
test/app/extend/context.test.js
test/fixtures/apps/get-logger/app/router.js
test/fixtures/apps/get-logger/config/config.js
test/fixtures/apps/get-logger/package.json
test/lib/core/urllib.test.js
test/utils.js

app and ctx
it can be override with custom function
Closes eggjs/egg#36

feat: add getLogger to app and ctx

---

config/config.local.js
config/config.unittest.js
lib/core/logger.js

logger
consoleLevel on unittest is WARN, so it should be print,
but egg disable console after app ready.
so enable console on unittest env
Closes eggjs/egg#127

feat: print error to console on unittest env

---

lib/egg.js
test/app/extend/context.test.js
test/fixtures/apps/agent-app/plugins/mock-client/mock_client.js
test/lib/agent.test.js
test/lib/cluster/master.test.js

refactor: use logger.close, .end is deprecated

---

docs/source/zh-cn/advanced/loader.md
docs/source/zh-cn/basics/app-start.md
docs/source/zh-cn/basics/config.md

docs: add advanced/loader.md

---

app/extend/agent.js
app/extend/application.js
docs/source/advanced/cluster.md
lib/cluster/index.js
lib/core/util.js
package.json
test/fixtures/apps/cluster_mod_app/agent.js
test/fixtures/apps/cluster_mod_app/app.js
test/fixtures/apps/cluster_mod_app/app/controller/home.js
test/fixtures/apps/cluster_mod_app/app/router.js
test/fixtures/apps/cluster_mod_app/config/config.default.js
test/fixtures/apps/cluster_mod_app/lib/registry_client.js
test/lib/cluster/cluster-client.test.js
test/lib/cluster/master.test.js
test/lib/core/util.test.js

feat: add cluster-client

---

docs/source/zh-cn/core/development.md

docs: add core/development.md

---

app/extend/request.js
config/config.default.js
test/app/extend/request.test.js
test/fixtures/apps/demo/config/config.default.js
test/fixtures/apps/secure-app/config/config.default.js

- 增加 `app.config.proxy` 用于标明应用是否在一个反向代理之后。
- host, ips 和 protocol 都支持配置 `app.config.[*]Headers`
- host 不存在时返回空字符串（**breaking  change**）
closes #212 #215

feat: support app.config.proxy to identify app is behind a proxy

---

app/extend/context.js
examples/cookie/app/controller/forget.js
examples/cookie/app/controller/home.js
examples/cookie/app/controller/remember.js
test/fixtures/apps/demo/app/controller/hello.js
test/fixtures/apps/encrypt-cookies/app/controller/home.js
test/fixtures/apps/secure-app/app/controller/index.js
test/lib/core/cookies.test.js

cookie
去除无意义的封装，保持和 koa 接口一致。
closes #181

refactor: remove ctx.getCookie, ctx.setCookie and ctx.deleteCookie

---

docs/source/zh-cn/basics/service.md

docs: add service doc

---

docs/source/zh-cn/practice/mysql.md

docs: add mysql doc

---

docs/source/zh-cn/intro/quickstart.md

1）默认脚手架生成的工程「egg-init egg-init egg-example --type=simple」中路由写到的/home了
2）this.ctx.curl(url, { dataType: 'json' })的返回值非promise对象，使用.then()会报错
3）需config中增加serverUrl、pageSize的值

docs: modify and fix 3 points

---

docs/source/zh-cn/basics/router.md

1）curl地址没带name参数值，会路由不到
2）没有设置csrf的post请求，直接curl模拟post会经过egg-security执行验证时报错‘secret is missing’

docs: add egg-security config to router docs

---

app/extend/context.js
lib/core/context_httpclient.js
lib/egg.js
test/app/extend/context.test.js

curl
curl return promise to support async functions

feat: curl return promise

---

app/extend/context.js
docs/source/zh-cn/advanced/view-plugin.md
test/fixtures/apps/view-render/app/controller/async.js
test/fixtures/apps/view-render/app/router.js
test/lib/plugins/view/render.test.js

view
remove generator function api to support async functions

feat: view base promise to support async function

---

.eslintrc
test/async/_async.js
test/async/index.test.js
test/fixtures/apps/async-app/app.js
test/fixtures/apps/async-app/app/controller/api.js
test/fixtures/apps/async-app/app/middleware/async.js
test/fixtures/apps/async-app/app/middleware/router.js
test/fixtures/apps/async-app/app/router.js
test/fixtures/apps/async-app/app/schedule/async.js
test/fixtures/apps/async-app/app/service/api.js
test/fixtures/apps/async-app/config/config.default.js
test/fixtures/apps/async-app/package.json

test
增加 async 相关的测试用例，需要等 egg-core 发布新版和 node 7.6 发布。

test: add async test case

---

docs/source/_data/guide_toc.yml
docs/source/zh-cn/basics/controller.md
docs/source/zh-cn/basics/middleware.md
docs/source/zh-cn/tutorials/async-function.md
docs/themes/egg/languages/zh-cn.yml

docs: add async await

---

docs/source/_data/menu.yml
docs/source/en/intro/quickstart.md
docs/source/zh-cn/intro/quickstart.md
docs/source/zh-cn/tutorials/async-function.md
docs/source/zh-cn/tutorials/index.md
docs/themes/egg/layout/partial/footer.swig

- add tutorials index, releate #354 
- fix async function dup docs https://github.com/eggjs/egg/pull/357

docs: add tutorials index & fix async

---

docs/source/_data/guide_toc.yml
docs/source/zh-cn/resource.md
docs/source/zh-cn/tutorials/async-function.md
docs/themes/egg/languages/zh-cn.yml
scripts/doc.js
test/fixtures/apps/logger-level-debug/app/router.js
test/lib/core/messenger.test.js

Closes https://github.com/eggjs/egg/issues/287

docs: add resource page

---

app/middleware/notfound.js
config/config.default.js
docs/source/zh-cn/core/error-handling.md
test/app/middleware/notfound.test.js

notfound
remove `notfound.enableRedirect`, always redirect if `notfound.pageUrl` present, ensure has the same behavior in different environments.

[BREAKING CHANGE] feat: remove notfound.enableRedirect

---

docs/source/zh-cn/basics/controller.md

原文档中 https://eggjs.org/zh-cn/basics/controller.html#jsonp-配置 的配置说明是
```
module.exports = {
callback: 'callback', // 识别 query 中的 `callback` 参数
limit: 100, // 函数名最长为 100 个字符
}
```
实际上应为
```
exports.jsonp = {...}
```

docs: 修正Controller文档中关于jsonp配置的错误

---

lib/egg.js
test/lib/application.test.js

fix: deprecate warning when inspect & toJSON

---

CONTRIBUTING.md

docs:correct spelling mistake

---

docs/source/en/intro/quickstart.md
docs/source/zh-cn/intro/quickstart.md
docs/source/zh-cn/tutorials/index.md

close https://github.com/eggjs/egg/issues/508

docs(quickstart): fix keys

---

lib/agent.js

feat: show warning message with call stack

---

docs/source/zh-cn/basics/router.md
lib/egg.js
test/fixtures/apps/cluster_mod_app/app.js

plugin development
```js
const cluster = app.cluster;
const client = cluster(XXXClient).create();
// ...
```

refactor: app.cluster auto bind this

---

docs/source/zh-cn/core/httpclient.md

docs: fix HttpClient link in docs

---

History.md
package.json

Closes https://github.com/eggjs/egg/issues/5

chore: Release the first stable version :egg: :clap::clap::clap:

---

docs/source/en/faq.md
docs/source/zh-cn/faq.md

https://github.com/eggjs/egg/issues/428

docs: turn off safe write in Jetbrains softwares

---

docs/source/zh-cn/basics/env.md

Fixed table render error in environment document.

docs: fix table render error in env.md

---

docs/source/zh-cn/core/security.md

The code example about CSRF for AJAX In jQuery, to get token from cookie, should be Cookies.get('csrfToken'), cause the default cookieName u set is 'csrfToken', ^_^.

docs(security):Cookie of token, the key must be csrfToken,

---

docs/source/zh-cn/core/cluster-and-ipc.md

-  The `framework.md` docs path changed, this reference docs didn't change。

docs: fix reference framework path

---

config/config.default.js
lib/application.js
test/fixtures/apps/confused-configuration/config/config.default.js
test/fixtures/apps/confused-configuration/package.json
test/lib/application.test.js

feat: warn if some confused configurations exist in config

---

docs/source/en/intro/quickstart.md
docs/source/zh-cn/intro/quickstart.md

docs(quickstart): tip for controller and config style

---

docs/source/zh-cn/basics/middleware.md
docs/source/zh-cn/core/security.md

docs: security match and ignore

---

README.md

docs: little grammar issues fixed in README.md

---

app/extend/context.js
lib/egg.js
test/app/extend/context.test.js
test/fixtures/apps/custom-context-getlogger/app/controller/home.js
test/fixtures/apps/custom-context-getlogger/app/extend/context.js
test/fixtures/apps/custom-context-getlogger/app/router.js
test/fixtures/apps/custom-context-getlogger/config/config.default.js
test/fixtures/apps/custom-context-getlogger/package.json

feat: export context base classes on Application

---

docs/source/zh-cn/core/development.md

docs: add vscode debug (#751)

---

README.md
README.zh-CN.md
docs/plugins.puml

chore: generate puml

---

config/config.local.js
test/lib/core/logger.test.js

This config is removed by PR #695,
but the infomation of coreLogger is not useful for app developer,
and this config won't changed by app developer

refactor: set consoleLevel WARN of coreLogger in local

---

lib/application.js

rename private method use es6 symbol to make method truely private.

refactor: rename private method name to symbol

---

docs/source/_data/guide_toc.yml
docs/source/languages/en.yml
docs/source/languages/zh-cn.yml
docs/source/zh-cn/basics/objects.md

docs: add document for built-in objects

---

docs/source/zh-cn/core/cookie-and-session.md

无
cookie.set/set时的签名属性为`signed`，但文档中写成`sign`了
closes #931

docs: fix spell error from sign to signed

---

config/config.default.js
docs/source/zh-cn/core/httpclient.md

fix: maxSockets Infinity value may set to null sometimes

---

docs/source/zh-cn/core/cluster-and-ipc.md
lib/application.js

**Description of change**
fix typo：
- anonymouse -> anonymous
- fix some typo in cluster-and-ipc.md

docs: typo

---

test/lib/application.test.js

fix https://travis-ci.org/eggjs/egg/jobs/245671138

test: wait logger to flush

---

.gitignore
docs/source/en/basics/config.md
docs/source/en/intro/quickstart.md
docs/source/zh-cn/basics/config.md
docs/source/zh-cn/intro/quickstart.md

docs: unify config in quickstart

---

docs/source/zh-cn/basics/objects.md

docs: adjust objects docs

---

lib/application.js
test/app/extend/application.test.js
test/fixtures/apps/app-locals-getter/app/router.js
test/fixtures/apps/app-locals-getter/config/config.default.js
test/fixtures/apps/app-locals-getter/package.json
test/fixtures/apps/locals/app/router.js

lib/application
No more cache the intermediate locals for Application.

fix: don't cache the intermediate locals for application

---

config/config.default.js
lib/core/utils.js
test/fixtures/apps/demo/config/config.default.js
test/lib/egg.test.js

feat: ignore any key contains "secret"

---

docs/source/zh-cn/core/development.md
scripts/doc_travis.sh

change docs:  [https://eggjs.org/zh-cn/core/development.html#使用-vscode-进行调试](https://eggjs.org/zh-cn/core/development.html#使用-vscode-进行调试)
references: [https://github.com/Microsoft/vscode/issues/30629#issuecomment-315196813](https://github.com/Microsoft/vscode/issues/30629#issuecomment-315196813)
Closes #1206

docs: new VScode 1.14 default protocol changed.

---

docs/source/en/basics/controller.md
docs/source/zh-cn/basics/controller.md

docs(controller): examples use controller class

---

docs/source/en/core/error-handling.md

docs(core/error-handling): translate error-handling.md in English

---

config/config.default.js
test/lib/core/loader/config_loader.test.js

feat: set cluster options, include path, port, hostname

---

docs/source/zh-cn/core/deployment.md
test/fixtures/apps/app-server-with-hostname/app/router.js
test/fixtures/apps/app-server-with-hostname/config/config.default.js
test/fixtures/apps/app-server-with-hostname/package.json
test/lib/cluster/app_worker.test.js

test: add test and doc for listen options

---

docs/source/zh-cn/core/unittest.md

docs(unittest): add bootstrap usage

---

docs/source/zh-cn/core/deployment.md

https://github.com/eggjs/egg-scripts/pull/1

docs: add egg-scripts to deployment

---

lib/core/httpclient.js
package.json
test/fixtures/apps/httpclient-tracer/app.js
test/fixtures/apps/httpclient-tracer/config/plugin.js
test/fixtures/apps/httpclient-tracer/package.json
test/lib/core/httpclient.test.js

如果 httpclient.request 的时候, 没有 ctx, 自动在 args 中设置 tracer.

feat: support app.httpclient and agent.httpclient auto set tracer

---

docs/source/en/core/httpclient.md
docs/source/zh-cn/core/httpclient.md

docs/source/en/core/i18n.md
docs/source/zh-cn/core/i18n.md
Translated https://github.com/eggjs/egg/blob/master/docs/source/zh-cn/core/httpclient.md
and minor revise the format of zh-cn:
1. revised the link of #options-参数详解 and a unknown symbol
2. Need further review below example. Don't have the comment in the original files and  the example is a little confuse that don't have the comma or semicolon between parameters. Might refer to [liburl ](https://github.com/node-modules/urllib#global-response-event)
```
请求发送之前，会触发一个 `request` 事件，允许对请求做拦截。
```js
app.httpclient.on('request', req => {
req.url 请求 url
req.ctx 是发起这次请求的当前上下文
// 可以在这里设置一些 trace headers，方便全链路跟踪
});
```
请求结束之后会触发一个 `response` 事件，这样外部就可以订阅这个事件打印日志。
```js
app.httpclient.on('response', result => {
result.res.status
result.ctx …

docs: (core/httpclient): [translate] Done 

---

docs/source/zh-cn/core/cluster-and-ipc.md

N/A
修复文档[多进程模型和进程间通讯](https://eggjs.org/zh-cn/core/cluster-and-ipc.html)中的部分书写错误

docs(core/cluster-and-ipc): fix some typo

---

docs/source/en/basics/objects.md
docs/source/zh-cn/basics/objects.md
index.js
test/index.test.js
test/lib/egg.test.js

Ref https://github.com/eggjs/egg/issues/1468

feat: add Subscription

---

History.md
package.json

Release 1.10.0

---

docs/source/en/core/cluster-and-ipc.md

Change-Id: I0ae00fde7e428582c2dd824489b7fd21184236c5
translate core/cluster-and-ipc.md

docs: translate core/cluster-and-ipc.md

---

docs/source/en/core/error-handling.md
docs/source/zh-cn/core/error-handling.md

related PR: https://github.com/eggjs/egg-onerror/pull/26

docs: how to customize error handler

---

docs/source/en/intro/quickstart.md
docs/source/zh-cn/intro/quickstart.md

docs(quickstart): generator -> async

---

docs/source/en/basics/app-start.md
docs/source/zh-cn/basics/app-start.md

docs(app-start): generator -> async

---

docs/source/languages/th.yml

Add th.yml in languages

---

docs/source/en/basics/middleware.md
docs/source/zh-cn/basics/middleware.md

docs(middleware): use async

---

docs/source/en/intro/quickstart.md
docs/source/zh-cn/intro/quickstart.md

docs(quickstart): use app.router

---

docs/source/en/core/i18n.md
docs/source/zh-cn/core/i18n.md

docs(i18n): use async

---

docs/source/zh-cn/core/deployment.md

https://github.com/eggjs/egg-scripts/pull/16

docs(deployment): adjust with new version egg-scripts

---

docs/source/en/intro/egg-and-koa.md
docs/source/en/intro/quickstart.md

docs(intro): make some changes for egg-and-koa

---

docs/source/en/basics/controller.md
docs/source/zh-cn/basics/controller.md

- closes #1769 
- closes #1755

docs(controller): import base controller directly

---

docs/source/en/basics/router.md
docs/source/zh-cn/basics/router.md

docs(router): new style & remove app.verb

---

docs/source/en/core/error-handling.md
docs/source/en/tutorials/restful.md
docs/source/zh-cn/core/error-handling.md
docs/source/zh-cn/tutorials/restful.md

2. docs(rest): yield -> await.

docs: fix async

---

docs/source/en/core/view.md

Start to work on translation of core/view

docs(core/view.md): translation

---

docs/source/zh-cn/tutorials/passport.md

docs(passport): add description

---

.gitignore
lib/application.js
test/lib/cluster/app_worker.test.js

application
Egg.js will do no response while client error. This PR makes server response a 400 Bad Request instead.
+ Refs: https://zhuanlan.zhihu.com/p/31966196
+ Refs: https://nodejs.org/dist/latest-v8.x/docs/api/http.html#http_event_clienterror

feat: add 400 response for broken client request to instead of empty response

---

test/app/extend/response.test.js
test/lib/core/cookies.test.js
test/lib/core/utils.test.js

Since new Buffer() was deprecated since Node.js v6. (https://nodejs.org/dist/latest-v8.x/docs/api/buffer.html#buffer_class_buffer)

chore: use Buffer.alloc, Buffer.from.

---

docs/source/en/basics/config.md

- fix some word spelling of basic-config

docs(basic-config): fix some word spelling

---

docs/source/en/basics/middleware.md

- fix some descriptions of basic-middleware based on my understanding
- fix some spellings errors

docs(basic-middleware):fix some descriptions of basic-middleware

---

History.md
package.json

release 2.2.1

---

docs/source/zh-cn/core/deployment.md

docs(deploy): add alinode

---

docs/source/zh-cn/core/deployment.md

docs(deploy): more about alinode

---

docs/source/en/basics/objects.md
docs/source/zh-cn/basics/objects.md

docs: add events on application

---

docs/source/en/basics/schedule.md
docs/source/zh-cn/basics/schedule.md

docs(schedule): logging && args

---

docs/source/en/basics/schedule.md

- fix some mistakes according to the Chinese versions

docs(schedule):fix some places

---

docs/source/zh-cn/basics/router.md

docs(router): add definition of ctx

---

docs/source/en/basics/router.md
docs/source/zh-cn/basics/router.md
index.d.ts

- close https://github.com/eggjs/egg/issues/2137
- doc fix

docs(ts): fix some d.ts

---

index.d.ts
test/fixtures/apps/app-ts/app/controller/foo.ts
test/fixtures/apps/app-ts/app/service/foo.ts

chore: change request.body and ctx.config type

---

app/middleware/meta.js
lib/application.js
test/app/middleware/meta.test.js

https://github.com/node-modules/agentkeepalive/issues/58

feat: support Keep-Alive Header

---

app/extend/context.js
test/app/extend/context.test.js
test/fixtures/apps/ctx-background/app/controller/custom.js
test/fixtures/apps/ctx-background/app/router.js

common use case like:
```js
const fn = function* (ctx) {}
fn.name = `some_${var}_${now)`;
```

fix: try to use custom function name first

---

config/config.default.js
test/app/extend/request.test.js

It's a security issue, x-forwarded-host can be retreived
from ctx.host when app.config.proxy is true, and be injected
to cookie domain.

fix: don't allow x-forwarded-host header

---

lib/egg.js

- ~~tests and/or benchmarks are included~~
- ~~documentation is changed or added~~
No
The developer will be less confused  when they run 
```js
console.log(app)
```
`console` will not swallow the `router` property of `app`
More information in https://github.com/eggjs/egg/issues/2228

feat: display router when log app

---

docs/source/en/basics/plugin.md

This PR is intended to provide an translation for `/basics/plugin.md` missing in #363 
I am not sure about the part
```
** Note: **
* `plugin.default.js` does not exists. Use `local` for dev environments.
* Use this feature only in the application layer. Do not use it in the framework layer.
```

docs: translation for basic plugin

---

docs/source/en/tutorials/mysql.md
docs/source/zh-cn/tutorials/mysql.md

`update` 方法，如果自定义主键名称不是 `id`，以下写法会报错：
```js
const row = {
custom_id: 123,
name: 'xx'
};
const result = await this.app.mysql.update('posts', row); 
```

修复 Mysql 教程 update 失败的问题

---

docs/source/en/core/security.md
docs/source/zh-cn/core/security.md

related:
- https://github.com/eggjs/egg-security/pull/30
- https://github.com/eggjs/egg-security/pull/31

docs: deprecate ignoreJSON

---

docs/source/en/advanced/plugin.md
docs/source/zh-cn/advanced/plugin.md

Recent I try to develop a egg plugin for my project，and was troubled by `addSingleton` function just because config file need `client` or `clients` key configuration as the config to the `creator` function。
And it seems that many people have encountered the same problem before.
- https://cnodejs.org/topic/59a5232ad97b7e2308242846
- https://github.com/eggjs/egg/issues/552
- https://github.com/eggjs/egg/issues/2226
- https://github.com/eggjs/egg/issues/1955

docs: plugin.md add config notice for `addSingleton`  function

---

docs/source/en/resource.md
index.d.ts

issue: https://github.com/eggjs/egg/issues/2292
[issue link](https://github.com/eggjs/egg/issues/2292)

chore(typings): change export interface to class definition

---

index.d.ts
package.json

chore: improve d.ts with ts support

---

docs/source/zh-cn/tutorials/passport.md

docs(passport): config passport-github behind of proxy

---

config/config.default.js
index.d.ts
lib/application.js
test/fixtures/apps/app-server-customized-client-error/app.js
test/fixtures/apps/app-server-customized-client-error/app/router.js
test/fixtures/apps/app-server-customized-client-error/config/config.default.js
test/fixtures/apps/app-server-customized-client-error/package.json
test/lib/cluster/app_worker.test.js
test/lib/core/httpclient.test.js

application
Add `onClientError` configuration to customize handling client error and get `rawPacket`.

feat: support customized client error

---

docs/source/en/basics/controller.md
docs/source/zh-cn/basics/controller.md

docs(controller): add ctx.redirect

---

.vscode/settings.json
docs/source/_data/guide_toc.yml
docs/source/en/tutorials/assets.md
docs/source/en/tutorials/typescript.md
docs/source/languages/en.yml
docs/source/languages/th.yml
docs/source/languages/zh-cn.yml
docs/source/zh-cn/tutorials/typescript.md

docs: add TypeScript Guide

---

index.d.ts
test/ts/index.test.js

EggAppConfig 有索引签名后才方便在  `config.default.ts` 等配置文件内扩展 config 对象。不然 tsc 的时候会报错

chore(typings): add index signature of EggAppConfig

---

docs/source/en/tutorials/passport.md
docs/source/zh-cn/tutorials/passport.md

Added passport tutorial English documentation  #363

EN translation for passport tutorial

---

docs/source/en/advanced/plugin.md
docs/source/zh-cn/advanced/plugin.md

docs(plugin): add singleton support async create function

---

README.zh-CN.md
app/extend/context.js
app/extend/request.js
app/extend/response.js

Change Logs:
1）/egg/README.zh-CN.md：Line 66 to 68 (Translate English part to
Chinese in README.zh-CN.md）.
2）/egg/app/extend/request.js：Line 181 (Correct English syntaxes
error).
3）Comments added for:app/extend/context.js
4）Comments merged for:
4.1）app/extend/request.js
4.2）app/extend/response.js
**Why to merge comments for properties?**
It's that properties get/set is reguarded as a "whole property", this
means you ONLY need to write one snippet of comments on either "get" or "set"
(usually on the 1st part).
If you write two snippets of comments on both get and set, if you move
your mouse onto the property,You'll find either get or set will have a wrong intellisense tip of
comments.

Docs (for some js files and README.zh-CN.md) Modifications of comments and full translations

---

config/config.default.js
lib/loader/app_worker_loader.js

Change logs:
**1) Fixes：**
/egg/config/config.default.js：Fix the error link of "security keys" to a right one in English.
**2) Changes：**
/egg/lib/loader/app_worker_loader.js：Translations from English ones to some Chinese comments.

Docs: Fix an error link, change a comment into English

---

lib/agent.js

Change logs:
1) /egg/lib/agent.js：do => doesn't, due to the syntax error.

Docs: Correct an error syntax of English

---

index.d.ts

In the past ``Application.locals`` and ``Context#locals`` are defined to be ``any``,
which makes developers not able to defined their type of ``locals``.
Now after these changes. Developers can easily defined ``locals``:
```
// index.d.ts
declare module 'egg' {
export interface IApplicationLocals {
foo: number;
}
export interface IContextLocals {
foo: number;
}
}
```

feat(d.ts): make app.locals and ctx.locals definitions merging available

---

index.d.ts

reloadOnDebug - whether reload on debug, default is true.
overrideDefault - whether override default watchDirs, default is false.
reloadPattern - whether to reload, use https://github.com/sindresorhus/multimatch

 feat(d.ts): add property of EggAppConfig.development

---

index.d.ts

https://github.com/eggjs/egg/issues/2644
因为最近 koa 发的 typings 版本，在 Context 中将 `[key: string]: any` 去掉了，所以在我们这里补上。
在想 `EggApplication` 是否也需要加上 key any 参数，来保证至少不会抛编译错误？

fix: add key any to Context

---

index.d.ts

chore(typings): add Messenger

---

docs/source/en/tutorials/socketio.md
docs/source/zh-cn/tutorials/socketio.md

```
> If you want to replace the default `ws` with [uws](https://github.com/uWebSockets/uWebSockets), you can config like this:
exports.io = {
init: { wsEngine: 'uws' },  // default 'ws'
};
```
- [#L106](https://github.com/socketio/engine.io/blob/6a16ea119280a02029618544d44eb515f7f2d076/lib/server.js#L106)

docs: fix ws engine error

---

test/lib/core/httpclient.test.js

It's introduced by https://github.com/node-modules/urllib/pull/288

test: skip test

---

index.d.ts

chore(typings): define Messenger['on'] and Messenger['once']

---

docs/source/en/core/deployment.md
docs/source/zh-cn/core/deployment.md

egg-scripts limited support for windows
see [#22](https://github.com/eggjs/egg-scripts/pull/22)

docs(deployment): egg-scripts support windows

---

app/middleware/meta.js

* :zap: use Math.floor instead of parseInt, based on performance and readability.
* More: https://github.com/eggjs/egg/pull/2702

:zap: use Math.floor instead of parseInt

---

docs/source/en/tutorials/restful.md
docs/source/zh-cn/tutorials/restful.md

优化在文档 restful API 章节中， egg-validate 的使用，由原来的 ctx.validate(rule) 调整为 ctx.validate(rule, ctx.request.body)。
因为自己参照文档学习使用 egg 开发 cnode 范例的时候，不知道传第二个参数（即被检测的对象），踩了这个坑。。

docs: optimize egg-validate usage

---

package.json

fix: add ms dependencies

---

docs/source/en/basics/config.md
docs/source/en/tutorials/socketio.md
docs/source/zh-cn/basics/config.md
docs/source/zh-cn/tutorials/socketio.md

- docs(socketio): format and add desc for uws
- docs(config): remove test from config list

docs: fix config and socketio error

---

README.zh-CN.md
package.json

1) Remove `bin` from `files`, it seems we don't have this folder.
2) Translation: We should include 8.x itself.

doc (package.json,README.zh-CN): Fix some typos

---

test/app/middleware/site_file.test.js

https://github.com/jshttp/mime-db/commit/0dc5b639550046e9940c052c13e7926976e6b81a#r30314927
这里带来的 breaking change，测试先修一下

test: fix sitefile icon test

---

History.md
package.json
test/lib/plugins/watcher.test.js

- 2.11.0 release
- fix 2.10.0 release note

Release 2.11.0

---

docs/source/en/basics/middleware.md
docs/source/zh-cn/basics/middleware.md
index.d.ts
package.json
test/fixtures/apps/app-ts/tsconfig.json
test/lib/agent.test.js

1) Compared with comments above 'bodyParser', we've missed 'ignore' and 'match'. So add them together into the 'index.d.ts' for TypeScript (Ref: https://github.com/eggjs/egg/issues/3006).
2) Update 'egg-mock' and fix a unit test in 'agent.test.js'.
3) Show detail info about 'ignore' and 'match' in both Chinese and English docs.

fix(typescript): Add missing `ignore/match`

---

lib/egg.js
test/lib/egg.test.js

refactor: separate dumping config object and config file

---

docs/source/en/tutorials/typescript.md
docs/source/zh-cn/tutorials/typescript.md

1) Add the missing English translations.
2) Format the Chinese TypeScript to make better look.

doc (typescript.md): Add missing trans in English for TypeScript

---

.autod.conf.js
package.json

the author of `circular-json` recommended `flatted` to replace `circular-json`
but `flatted`'s output is too different with JSON.stringify which don't fit our needs

deps: pin circular-json@0.5.5 to avoid output deprecate message

---

docs/source/en/tutorials/typescript.md
docs/source/zh-cn/tutorials/typescript.md

1) Some parts aren't translated into Chinese, so tranlate them
all in the Chinese version.
2) There're some formations error in JSON snippets in both Chinese and English versions, so fix them all：
e.g——

chroe (TypeScript): Formation errors with missing translations fixed

---

docs/source/en/basics/objects.md
docs/source/zh-cn/basics/objects.md

1) 'app....' should be 'this.app....'.
2) 4 levels instead of 5 for each logger instance.
Ref:
1) https://github.com/eggjs/egg/pull/3019
2) https://github.com/eggjs/egg/pull/3018

doc (objects.md): Fix number and code errors

---

package.json
test/lib/core/dnscache_httpclient.test.js

closes https://github.com/eggjs/egg/issues/3033

test: avoid DNS pollution on local env

---

docs/source/en/tutorials/socketio.md
docs/source/zh-cn/tutorials/socketio.md

Make sure that 'uws' is deprecated due to the known issue.

docs (socket.io.md): Modify some statements

---

lib/egg.js
test/fixtures/apps/schedule/app/schedule/hello.js
test/fixtures/apps/schedule/app/schedule/sub/cron.js
test/lib/plugins/schedule.test.js

feat: add Subscription base class on app instance

---

package.json

deps: egg-logger@2

---

docs/source/en/core/logger.md

1) Correct logger's default output level in production env. in this doc from 'higher than INFO' to 'higher than DEBUG'.
2) Rephrase the description about log level to avoid confusion.
修改了英文文档`logger.md`中对于默认日志级别的错误，从原版本的`INFO以上才写入`改为了`DEBUG以上才写入`。并且略微润色完善了上下文对于日志级别的一些描述以避免误解。

doc(logger.md): Fix incorrect description on default log output level.

---

CONTRIBUTING.md
CONTRIBUTING.zh-CN.md
lib/core/dnscache_httpclient.js
test/lib/core/dnscache_httpclient.test.js
test/lib/core/httpclient.test.js

1) Due to different service providors have a variety ways of coping with
a dns that cannot be analysed, we have to make it clear to users that
dns unit tests may fail (See: #3033).
2) Comment out a skip unit test in 'httpclient.test.js', no need to show
the 'pending' state but with comments above.
3) Add missing English part in CONTRIBUTING.md.
4) Change the warning info, because we can still use this callback but
NOT recommended.

doc (CONTRIBUTION): Add missing English translations and clearify dns

---

docs/source/en/basics/controller.md
docs/source/zh-cn/basics/controller.md

Ref atian25's suggestions at: https://github.com/eggjs/egg/pull/3066.

docs(CONTRIBUTION): Add missing link for `Accquire the submitted files`

---

app/extend/context.js
test/app/extend/context.test.js

对 `runInBackground` 核心使用上没有影响，只是当 `catch()` 到错误时，往 app emit 一个事件
对应用性能影响方面可能需要评估
背景：目前 `runInBackground` 相当于吞掉了异常，默认做了 log，使用方如果想统一收集错误做报表或监控，目前会丢失掉这部分
解决方案：
其实当时想到两种方案
1. 自定义一个 `ctx.customRunInBackground`，在 `runInBackground` 内层自己先包裹 `try catch` 然后把错误收集起来，但是这个方法感觉太挫，而且旧有使用 `runInBackground` 的代码都得 change
2. 在原有 `runInBackground` 的 catch 逻辑里增加事件的暴露，就是这个 mr 的方案

fix: runInBackground should emit error event

---

index.d.ts

I try to write a plugin and I noticed that no `beforeClose` method.
typings
add `beforeClose` definition

chore(typings): add method `beforeClose` in index.d.ts

---

.gitignore
LICENSE
config/config.default.js
docs/source/en/core/httpclient.md
docs/source/zh-cn/core/httpclient.md
index.d.ts
lib/core/httpclient.js
package.json
test/fixtures/apps/context_httpclient_timeout/config/config.default.js
test/fixtures/apps/context_httpclient_timeout/package.json
test/lib/core/context_httpclient_timeout.test.js
test/lib/core/httpclient.test.js

closes https://github.com/eggjs/egg/issues/3140
agentkeepalive@4 support node >= 8.0.0

fix: allow request timeout bigger than agent timeout

---

lib/egg.js
test/lib/egg.test.js

Lifecycle
When worker restart, master process broadcast `egg-ready` event to all workers, so worker should listen `egg-ready` only once.

fix: triggerServerDidReady should be triggered only once

---

index.d.ts

feat(index.d.ts): curl 增加泛型

---

docs/source/en/core/cookie-and-session.md
docs/source/zh-cn/core/cookie-and-session.md

1) Fix some English translations for 'cookies-and-session.md' file.
2) Union some icons for 'Right' and 'Wrong'.

doc: Fix some translations with some icons

---

index.d.ts

原来 egg 的 context 声明是继承自 `koa.Context` 的，但是 egg 里的 context 中的部分属性 `cookie` 跟 koa 里的不是同一个，因此会产生类型不兼容 ( 在 `skipLibCheck` 为 false 的情况下跑 tsc 会报错 )。
在原来的解决方案中，是通过 `RemoveSpecProp` 这个工具类型将 `koa.Context` 中的 cookie 属性删掉再继承，但是最近 koa 的声明发了个版本在 context 声明上加了 `[key: string]: any` ，加了这个声明后就导致 `keyof koa.Context` 拿到的类型就错了，导致现在拿不到 `koa.Context` 里的声明。
我想到的解决方案是直接用 koa 内部的 `BaseContext` 类型，然后将 `req` 这些在 `koa.Context` 中的属性在 `Context` 中重新写一遍，以此来解决类型兼容问题。
https://github.com/eggjs/egg/pull/2958#issuecomment-448485177

fix: context declaration not works

---

index.d.ts

Because the version of Koa is updated to the latest version,
we cannot simply remove properties but just re-write properties
from the inherited ones. Add more comments on this.
Ref：https://github.com/eggjs/egg/pull/3329

fix: Add comments for re-writing properties from Koa

---

docs/assets/lifecycle_en.puml
docs/source/en/advanced/loader.md
docs/source/en/basics/controller.md
docs/source/en/basics/plugin.md
docs/source/en/core/security.md
docs/source/en/intro/index.md
docs/source/en/intro/quickstart.md
docs/source/en/tutorials/typescript.md
docs/source/zh-cn/intro/index.md
docs/source/zh-cn/tutorials/typescript.md
package.json

1. For "Sails" in both Chinese and English versions, we should also add the links for them.
2. Union the spellings of "Plugin" instead of "Plug-in".
**3. IMPORTANT!! 
Update to the latest version of Typescript, because yard has used "unknown" type, which MUST BE supported since v3.X.**
Here's the screenshot before update:

Chore: Fix spellings and update typescript compiler version to 3.X

---

docs/source/en/advanced/loader.md

Due to the image isn't generated properly in the center, so we have to re-create it for "loader.md" (English version).

doc (loader.md): Update the diagram of "starting process"

---

docs/source/zh-cn/tutorials/typescript.md

更新优化关于 typescript 的使用文档，添加常见问题描述，英语版就等 merged 后 @Maledong  补一下？

docs(typescript): optimize docs of typescript

---

docs/source/en/tutorials/typescript.md
docs/source/zh-cn/advanced/loader.md
docs/source/zh-cn/tutorials/typescript.md

**1) typescript.md (English version):**
Use ` instead of '.
**2) loader.md (Chinese version):**
Translation 'loadUnit'.
**3) typescript.md (Chinese version):**
Remove duplicated space.
---

Chore: Fix some chore issues

---

docs/source/en/basics/plugin.md
docs/source/zh-cn/basics/plugin.md
docs/source/zh-cn/core/httpclient.md

docs:Wrong words are corrected

---

index.d.ts

egg-static plugin supports array of paths for the config property `dir`.
fix type defined in `index.d.ts`.

fix(types): array supporting for config.static.dir

---

docs/source/en/tutorials/sequelize.md
docs/source/zh-cn/tutorials/sequelize.md

closes https://github.com/eggjs/egg/issues/3442

docs(sequelize): fix init doc

---

lib/core/messenger/local.js
test/lib/core/messenger/local.test.js

fix local messenger:
- `send()` support without `to`
- `send()` don't throw before app/agent ready and assigned

fix: support send without to argument

---

index.d.ts
test/fixtures/apps/app-ts/app/controller/foo.ts
test/fixtures/apps/app-ts/app/extend/context.ts
test/fixtures/apps/app-ts/app/extend/helper.ts
test/fixtures/apps/app-ts/app/extend/index.d.ts

将 IHelper 改成继承 BaseContextClass ，在写 helper 的 extend 的时候，将 this type 指定为 IHelper 才能拿到 `this.ctx` ，顺便将 BaseContextClass 里的 ctx、app 等改成 protected ，在外部使用的时候就不会出现这些干扰类型。

fix: helper type

---

docs/source/zh-cn/tutorials/typescript.md

Since we have a Chinese version of TypeScript, so we can directly refer it instead of referring an English introduction.
---

doc (typescript.md): Chinese translation for the beginning of TypeScript's Introduction

---

index.d.ts

fix: method getFileStream is lack of parameter types
line: 679 add interface GetFileStreamOptions
line: 909 add '@param {Object} options'
line: 913 modify getFileStream() to getFileStream(options:GetFileStreamOptions)

fix: getFileStream options types

---

lib/start.js
test/lib/start.test.js

feat: single mode support ignore warning

---

test/lib/cluster/cluster-client.test.js

Since 'cluster-client@3.0.1' has fixed something imcompatable, so we
should rollback this unit test.
---

Fix(cluster-client.test.js)：Rollback 

---

docs/source/en/core/httpclient.md
docs/source/zh-cn/core/httpclient.md

close https://github.com/eggjs/egg/issues/3568

docs(httpclient): update http_proxy usage

---

docs/source/_data/guide_toc.yml
docs/source/en/tutorials/proxy.md
docs/source/languages/en.yml
docs/source/languages/zh-cn.yml
docs/source/zh-cn/tutorials/proxy.md

docs: add how to config egg behind a proxy

---

app/extend/context.js
app/extend/helper.js
app/extend/request.js
app/extend/response.js
index.d.ts
lib/agent.js
lib/application.js
lib/core/base_context_logger.js
lib/core/httpclient.js
lib/egg.js
test/app/extend/context.test.js
test/fixtures/apps/httpclient-retry/package.json
test/lib/core/httpclient.test.js
test/utils.js

close https://github.com/eggjs/egg/issues/2467

feat: switch httpclient to httpclient2 for retry feature

---

app/extend/context.js
app/extend/helper.js
app/extend/request.js
app/extend/response.js
lib/agent.js
lib/application.js
lib/core/base_context_logger.js
lib/egg.js

chore: fix jsdocs

---

agent.js
index.d.ts
index.js
lib/agent.js
lib/core/base_hook_class.js
lib/egg.js
package.json
test/agent.test.js
test/fixtures/apps/agent-logger-config/config/config.default.js
test/fixtures/apps/agent-logger-config/package.json
test/fixtures/apps/boot-app/agent.js
test/fixtures/apps/boot-app/app.js
test/index.test.js
test/lib/core/loader/load_boot.test.js
test/lib/egg.test.js

Fixes: 
- https://github.com/eggjs/egg/issues/3548
- https://github.com/eggjs/egg/issues/3454

feat: lifecycle base class

---

docs/source/_data/guide_toc.yml
docs/source/en/plugins/index.md
docs/source/zh-cn/plugins/index.md
package.json
test/doc.test.js

1. The 'plugin' folder in both 'en' and 'zh-CN' is replaced by a direct
on-line search, so we don't need it anymore.
2. Make the doc build do validations when running 'test/doc.test.js'：
3. Update 'egg-bin' to '4.12.3'.
---

chore: update packages,remove 'plugin' and validations of doc generation

---

lib/agent.js
test/fixtures/apps/boot-app/agent.js
test/fixtures/apps/boot-app/app.js
test/lib/core/loader/load_boot.test.js

https://github.com/eggjs/egg/pull/3581/files#r279235776

fix: should restore agent messenger first

---

index.d.ts
test/fixtures/apps/app-ts-type-check/normal.ts

fix(typings): optimize declaration of httpclient

---

test/app/middleware/site_file.test.js
test/lib/core/view.test.js
test/lib/plugins/i18n.test.js
test/lib/plugins/static.test.js

on window platform, file content contains \r character.so some test failed on window platform.this pr fix it.so when developer work on it ,npm run test-local will  work better.

fix: some test methods failed on windows platform

---

package.json

```bash
npm WARN deprecated @types/urllib@2.33.0: This is a stub types definition. urllib provides its own type definitions, so you do not need this installed.
```

chore: remove @types/urllib

---

.travis.yml
test/lib/core/httpclient.test.js
test/lib/egg.test.js

chore: fix ci

---

lib/application.js
test/app/extend/application.test.js

The `handleRequest` method, which is inherited from `koa.Application`, The original method have a return value, it is a promise.

fix: handleRequest method should return a promise

---

lib/application.js
test/fixtures/apps/app-throw/app/router.js
test/lib/application.test.js
test/lib/egg.test.js

fix: error message rewrite when it has only a getter

---

test/fixtures/apps/dumpconfig/app.js
test/lib/egg.test.js

由于 `dumpConfig` 在 `app.ready()` 前后各一次，且创建时间无法确定，通过 `sleep` 方法检测在 `win` 存在不确定性，将其移动到 `fixtures` 下 `app.js` 中使用文件读取的方式进行检测。

test: mv assert to fixtures

---

.travis.yml
appveyor.yml

chore: add node12 for ci

---

docs/source/en/intro/egg-and-koa.md
docs/source/zh-cn/intro/egg-and-koa.md

docs(egg-and-koa): modify invalid links

---

lib/application.js
test/app/extend/application.test.js

fix: app.keys getter must have a setter either

---

docs/source/zh-cn/tutorials/socketio.md

https://socket.io/docs/client-api/#socket-disconnect
https://github.com/eggjs/egg/blob/master/docs/source/en/tutorials/socketio.md#197
https://github.com/eggjs/egg/pull/2167#discussion_r172859975

docs: fix typo of socket.io

---

config/config.default.js
test/app/middleware/body_parser.test.js
test/fixtures/apps/body_parser_testapp/config/config.default.js

- set `formLimit` to `1mb`
- set `jsonLimit` to `1mb`
- add `textLimit` config and set it to `1mb`
单测配置为 `100kb`，因为在测试用例中 console 方式输出 `1mb` 内容会导致测试用例异常。

feat: set default body-parser limitation to 1mb

---

.github/workflows/ci.yml
test/app/middleware/body_parser.test.js

chore: use github actions to run CI

---

docs/source/en/core/deployment.md
docs/source/zh-cn/core/deployment.md

抱歉没有认真阅读CONTRIBUTING和同时又新建了一个pull request。
按照部署文档所写的hostname部署到云服务器，无法被外网访问，需改成0.0.0.0。
```  
// config/config.default.js
exports.cluster = {
listen: {
port: 7001,
hostname: '127.0.0.1',
// path: '/var/run/egg.sock',
}
}
```
[中文文档锚点](https://eggjs.org/zh-cn/core/deployment.html#%E5%90%AF%E5%8A%A8%E9%85%8D%E7%BD%AE%E9%A1%B9)  
[英文文档锚点](https://eggjs.org/en/core/deployment.html#dispatch-with-arguments)

docs(deployment.md): modify hostname

---

lib/core/singleton.js
test/lib/core/singleton.test.js

Singleton在调用插件的create方法时，返回相应的配置中的实例名，用于插件内部判断是哪个实例化发生了错误。
相关issue：https://github.com/eggjs/egg/issues/3648

feat:Singleton returns client name when create client

---

docs/source/en/basics/env.md
docs/source/zh-cn/basics/env.md

documentation cleanup. I think using `config/env` is confusing for new learners. It actually represents the running mode as It only contains a single line.
I need to use `dotenv` in order to read env from a file.
What do u think?

docs: cleanup the document

---

app/extend/request.js
config/config.default.js
docs/source/en/tutorials/proxy.md
docs/source/zh-cn/tutorials/proxy.md
test/app/extend/request.test.js

feat: support config.maxIpsCount

---

test/lib/core/loader/load_boot.test.js

…in issue #4040
The 'app.mockLog' function in 'test/lib/core/loader/load_boot.test.js' should use 'app.coreLogger'
instead of the default 'app.logger', otherwise the 'app.expectLog' cannot get the contents in log
files.
fix #4040
Testcase 'should load app.js' in 'test/lib/core/loader/load_boot.test.js'
The 'app.mockLog' function in 'test/lib/core/loader/load_boot.test.js' should use 'app.coreLogger'
instead of the default 'app.logger', otherwise the 'app.expectLog' cannot get the expected content in log
files.

test: fix the testcase error of load_boot.test.js

---

lib/core/dnscache_httpclient.js
lib/core/utils.js
test/lib/core/utils.test.js

fix: use new URL instead of url.parse

---

.travis.yml
app/extend/context.js
config/config.default.js
docs/source/en/basics/controller.md
docs/source/zh-cn/basics/controller.md
package.json
test/doc.test.js
test/fixtures/apps/app-config-cookies/app/controller/home.js
test/fixtures/apps/app-config-cookies/app/router.js
test/fixtures/apps/app-config-cookies/config/config.default.js
test/fixtures/apps/app-config-cookies/package.json
test/lib/core/config/config.cookies.test.js

feat: add application level Cookie options

---

appveyor.yml
package.json
test/doc.test.js

test: fix doctools path on windows

---

docs/source/en/tutorials/socketio.md
docs/source/zh-cn/tutorials/socketio.md

this.packet is undefined, data in ctx.packet
https://github.com/eggjs/egg-socket.io/blob/576578ac6324580150af2c4e2cb67ac31d8d7dea/lib/packetMiddlewareInit.js#L15

doc (socketio): fix packet middleware bug

---

app/extend/context.js
test/app/extend/context.test.js
test/fixtures/apps/ctx-background/app/controller/sync.js
test/fixtures/apps/ctx-background/app/router.js

runInBackground will run after setImmedate

fix: runInBackground always run after setImmediate

---

app/middleware/meta.js
lib/egg.js
test/lib/egg.test.js

- 仅在启动成功后禁止新增 timing，不清理启动的 timing，让一些采集 timing 的插件有机会获取 
- 12.19 的 keep-alive 处理

fix: remove clear timing && skip keep-alive after 12.19.0

---

History.md
package.json

Release 2.29.1

---

index.d.ts

- [√] commit message follows commit guidelines
fix #4486

fix: add overrideIgnore define

---

docs/source/en/migration.md

No core subsystem is affected.
Added English translation to [migration.md](./docs/source/en/migration.md) under `en` folder.
添加了`en` 文件夹下的 [migration.md](./docs/source/en/migration.md) 英文版本。

docs: Added english doc to how-to-migrate-from-1.x

---

docs/source/zh-cn/core/cookie-and-session.md

Hey guys,
Just fix a petite typo, modified `登陆` to`登录`
No need to check this.
Nope
fix typo on doc

doc: Typo fixture:「登陆」->「登录」

---

docs/source/en/tutorials/typescript.md

Ref：https://github.com/eggjs/egg/pull/4666.
---

doc: Add the missing zh-CN trans for typescript

---

lib/core/dnscache_httpclient.js
test/fixtures/apps/dnscache_httpclient/app/controller/home.js
test/lib/core/dnscache_httpclient.test.js

can handle not use DNSCache in one request even though config set to `enableDNSCache: true`
sometime SDK should not want to use DNSCache by disaster retry，then it can handle not cache by itself

feat: support disableDNSCache by request args handle

---

app/extend/context.js
config/config.default.js
index.d.ts
lib/egg.js
package.json
test/app/extend/application.test.js
test/app/extend/context.test.js
test/fixtures/apps/app-enablePerformanceTimer-true/app/controller/home.js
test/fixtures/apps/app-enablePerformanceTimer-true/app/router.js
test/fixtures/apps/app-enablePerformanceTimer-true/config/config.default.js
test/fixtures/apps/app-enablePerformanceTimer-true/config/config.unittest.js
test/fixtures/apps/app-enablePerformanceTimer-true/package.json
test/fixtures/apps/tracer-demo/tracer.js
test/lib/core/context_performance_starttime.test.js

detail see https://github.com/eggjs/egg-logger/pull/74
How to use:
```js
// config.js
exports.logger = {
enablePerformanceTimer: true,
};
```

feat: support better logger timer in precise milliseconds

---

site/config/config.ts

Use Egg brand color (#22ab28) as the primary color of doc site

docs: use egg brand color for site

---

.github/workflows/chainalert.yml

https://github.com/Checkmarx/chainalert-github-action
See https://github.com/react-component/menu/issues/431

test: add ChainAlert action

---

.github/dependabot.yml
package.json
test/fixtures/apps/response/app/router.js

1. Upgrade @umijs/preset-react from 1.xx to 2.xx.
2. Use 'Buffer.alloc' instead of 'new Buffer()'.
3. Add 'dependabot.yml'to upgrade the related packages automatically.
---

chore: package upgrade and unittest fixture

---

.github/workflows/nodejs.yml
lib/egg.js
test/fixtures/apps/dumptiming-timeout/app.js
test/fixtures/apps/dumptiming-timeout/config/config.default.js
test/fixtures/apps/dumptiming-timeout/config/plugin.js
test/fixtures/apps/dumptiming-timeout/package.json
test/lib/egg.test.js

```bash
2022-06-17 10:50:12,770 ERROR 69291 application still doesn't ready after 1000 ms.
2022-06-17 10:50:12,770 ERROR 69291 unfinished timing item: {"name":"Application Start","start":1655434211766,"pid":69291,"index":1}
2022-06-17 10:50:12,771 ERROR 69291 unfinished timing item: {"name":"Did Load in app.js:didLoad","start":1655434211778,"pid":69291,"index":52}
2022-06-17 10:50:12,771 ERROR 69291 check run/application_timing_69291.json for more details.
```

feat: should log unfinished timing item

---

config/config.default.js
lib/core/httpclient_next.js
lib/egg.js
package.json
test/fixtures/apps/httpclient-next-with-tracer/config/config.default.js
test/fixtures/apps/httpclient-next-with-tracer/config/plugin.js
test/fixtures/apps/httpclient-next-with-tracer/package.json
test/lib/core/httpclient.test.js
test/lib/core/logger.test.js

closes https://github.com/eggjs/egg/issues/4847

feat: Support urllib@3

---

README.md
README.zh-CN.md

Upgrading the version for Egg3.0 by referring Node's 14.20.x or above.

docs: update the version of the required Node

---

package.json

https://github.com/eggjs/egg-multipart/pull/56
https://github.com/eggjs/egg/pull/5032

fix: update multipart 3.1.0

---

lib/egg.js
test/fixtures/apps/httpclient-next-overwrite/app.js
test/fixtures/apps/httpclient-next-overwrite/config/config.default.js
test/fixtures/apps/httpclient-next-overwrite/package.json
test/lib/core/httpclient.test.js

https://github.com/eggjs/egg/pull/5000

🐛 FIX: Allow override HttpClientNext

---

index.d.ts
lib/application.js
lib/egg.js

feat: runInAnonymousContextScope support req

---

test/app/extend/application.test.js
test/fixtures/apps/app-runInAnonymousContextScope-withRequest/app.js
test/fixtures/apps/app-runInAnonymousContextScope-withRequest/config/config.default.js
test/fixtures/apps/app-runInAnonymousContextScope-withRequest/config/config.unittest.js
test/fixtures/apps/app-runInAnonymousContextScope-withRequest/package.json
test/lib/cluster/app_worker.test.js

Since 'runInAnoymousContextScope' now has a new feature with a request as a parameter, it lacks a new test case, this is the test case for it.
Refs：https://github.com/eggjs/egg/pull/5134
---

test: add new test case for runInAnonymousContextScope

---

CONTRIBUTING.md
CONTRIBUTING.zh-CN.md

Add necessary detailled information for "Pulling code" and "Install Dependencies", especially for when npm's version >= 7.x, '--legacy-peer-deps' is always ignored by new comers, which will raise installation problems.
---

docs: add details for "pulling code" and "install dependencies"

---

test/lib/core/logger.test.js

After investigation for a while for windows, it seems we should delay for about 1 sec before the "assert" can find the actual error logged into the file.
---

test: fix the unstable for windows

---

test/fixtures/apps/demo/app.js
test/lib/egg.test.js

Bug Reasons:
1. We cannot get "messenger" and "lifecycle" instances belonging to "app" itself before "ready()" function, a "cannot get xxx property" will be raised.
2. We CANNOT use "mm(……)" to replace "triggerServerDidReady" function, after "app.ready()" in the unit test case, bcoz it WON'T be triggered if we do that. The only solution is to replace it in the constructor.
---

test: fix and enable 'egg.test.js'

---

package.json
test/doc.test.js
test/lib/core/logger.test.js
test/lib/egg.test.js

1. Update "findlinks" to make the "doc.test.js" stable when rendering documents of Egg.js (Refs: https://github.com/popomore/findlinks/pull/9).
2. Adjust the "utils.sleep()" to make sure the "test/lib/core/logger.test.js" on non-windows platform stable.
---

test: stable some unit tests

---

test/async/index.test.js
test/asyncSupport.test.js

Our current nodejs version MUST BE >=14.20.0, no need to check whether the current version satisfies the test env.
---

test: remove useless "async" support check

---

README.md
README.zh-CN.md

The old link cannot sync the state of "CI", and now GitHub has re-newed its link, this is the fix for it.
Refs: https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge#using-the-workflow-file-name
---

chore: fix "Continous Integrations" sync badge state

---

lib/core/messenger/ipc.js
package.json
test/lib/core/messenger/ipc.test.js

`lib/core/messenger`
Fix the issue where IPC does not work when startMode is set to 'worker_threads'.
This change depends on the modification made in "[sendmessage #3](https://github.com/node-modules/sendmessage/pull/3)". Please make sure that this change has taken effect before merging this one.

fix: ipc not work with worker_threads mode

---

.github/workflows/codeql-analysis.yml
.github/workflows/nodejs.yml
.github/workflows/release.yml
test/lib/plugins/development.test.js

test: make plugins/development test stable

---

test/lib/plugins/development.test.js

Refs: https://github.com/eggjs/egg/pull/5211.
---

test: add "expect" to "development" plugin tests

---

lib/start.js
test/lib/start.test.js

Since we're now successfully using this feature for a long time without obvious bugs/errors, there's no need for us to make it as an "experinment" feature and now it's come to ture.
Ref: https://github.com/eggjs/egg/pull/3430
---

chore: remove SingleProcess warnings

---

lib/egg.js

because of   production env shouldn't use inspector module and such as vercel/pkg custom node runtime remove it. so we hope egg disable inspector on production env.
closes https://github.com/eggjs/egg/issues/5226

fix: don't require inspector module on production env

---

site/docs/core/error-handling.zh-CN.md

fix doc typo

---

lib/core/base_context_logger.js

closes https://github.com/eggjs/egg/issues/5213#issuecomment-1657771583

fix: use app.logger instead of ctx.logger

---

site/docs/index.md
site/docs/index.zh-CN.md

doc: add recruit link

---

README.md

感觉可以在 README 加一下 PNPM 脚手架，看到之前有 issue 在混用 npm 和 pnpm:  [issue 4867](https://github.com/eggjs/egg/issues/4867), [issue 4739](https://github.com/eggjs/egg/issues/4739#issuecomment-1000619668)
ref: https://github.com/pnpm/pnpm/issues/7006#issuecomment-1707730166

docs: README adding optional pnpm scaffolding

---

lib/core/singleton.js

chore: typo fix on singleton.js

---

index.d.ts

`i18n.dir` should be `i18n.dirs`

fix: typo on index.d.ts

---

lib/core/logger.js
package.json
test/fixtures/apps/custom-logger/app/router.js
test/fixtures/apps/custom-logger/config/config.default.js
test/lib/core/loader/load_service.test.js
test/lib/core/logger.test.js

https://github.com/node-modules/onelogger

feat: auto set custom logger with onelogger

---

site/docs/basics/app-start.zh-CN.md
site/docs/basics/config.zh-CN.md
site/docs/basics/controller.zh-CN.md
site/docs/basics/env.zh-CN.md
site/docs/basics/extend.zh-CN.md
site/docs/basics/middleware.zh-CN.md
site/docs/basics/objects.zh-CN.md
site/docs/basics/plugin.zh-CN.md
site/docs/basics/router.zh-CN.md
site/docs/basics/schedule.zh-CN.md
site/docs/basics/service.zh-CN.md
site/docs/basics/structure.zh-CN.md

不涉及
利用 AI 实现的文档表达优化，主要包括：
1. 修正错别字、标点
2. 句式、表达语气、段落组织优化，让阅读更通顺
4. 个别代码和注释错误
PR 内容未经人工处理，修改准确性一般在 80% 左右，请在合并前充分审阅。

feat: 优化文档表达

---

site/docs/core/security.md
site/docs/core/security.zh-CN.md

doc: add revert doc

---

site/config/config.ts

chore(site): add artusjs links

---

lib/core/utils.js
test/lib/core/utils.test.js

According to AI's suggestions at https://github.com/eggjs/egg/pull/5302, it seems there're some missing unit tests and here's the fix for it.

test: add some missing unit tests for 'convertObject'

---

index.d.ts
test/app/middleware/body_parser.test.js

https://github.com/cojs/co-body/pull/87

feat: add bodyParser.onProtoPoisoning type define

---

index.d.ts

feat: add httpclient.safeCurl typing

---

.gitignore
index.d.ts
test/fixtures/apps/app-ts/app/controller/foo.ts

```bash
node_modules/.store/egg@3.30.0/node_modules/egg/index.d.ts:63:3 - error TS2666: Exports and export assignments are not permitted in module augmentations.
63   export { HttpClientRequestURL, HttpClientRequestOptions, HttpClientResponse };
~~~~~~
Found 1 error in node_modules/.store/egg@3.30.0/node_modules/egg/index.d.ts:63
```

fix: redefine urllib export types

---

site/docs/basics/controller.md
site/docs/basics/controller.zh-CN.md

closes https://github.com/eggjs/egg/issues/5411

chore: hostHeaders default value is empty string
