app/extend/response.js
package.json
test/app/extend/request.test.js
test/app/extend/response.test.js
test/fixtures/apps/response/app/router.js
test/fixtures/apps/response/package.json

fix: set header use lowercase

---

.gitignore
README.md
docs/source/_data/guide_toc.yml
docs/source/guide/installation.md
docs/themes/egg/languages/en.yml
docs/themes/egg/languages/zh-cn.yml

doc: update readme

---

README.md
README.zh-CN.md
docs/scripts/helpers.js
docs/themes/egg/languages/zh-cn.yml
docs/themes/egg/layout/partial/header.swig

document
- fix index link for zh-cn
- fix plugins link in readme

doc: fix index link for zh-cn

---

.gitignore
docs/source/advanced/best_practice.md
docs/source/advanced/cluster.md
docs/source/advanced/loader.md
docs/source/advanced/singleton.md
docs/source/advanced/write_framework.md
docs/source/advanced/write_plugin.md
docs/source/faq.md
docs/source/frameworks.md
docs/source/guide/deployment.md
docs/source/guide/index.md
docs/source/guide/installation.md
docs/source/guide/plugins.md
docs/source/guide/quickstart.md
docs/source/guide/unittest.md
docs/source/guide/write_application.md

doc: add title

---

docs/_config.yml
docs/source/guide/installation.md

doc: Add Installation

---

package.json

package.json
remove eslint --fix

chore: remove --fix for error check but not fix

---

app/extend/request.js
config/config.default.js

can improve 6x on node 6.x
see https://gist.github.com/fengmk2/d7d0091a5eeae8ce0c9580f31e748371

perf: get header using lower case

---

lib/core/app_worker_client.js
test/fixtures/apps/agent-client-app/agent.js
test/fixtures/apps/agent-client-app/app.js
test/fixtures/apps/agent-client-app/app/router.js
test/fixtures/apps/agent-client-app/package.json
test/lib/core/app_worker_client.test.js

pick patch from internal version

fix: AppWorkerClient subscribe same data failed issue

---

.travis.yml
appveyor.yml
package.json
test/app/extend/agent.test.js
test/app/extend/context.test.js
test/app/extend/request.test.js
test/fixtures/apps/watcher-development-app/app/router.js
test/lib/application.test.js
test/lib/core/logger.test.js
test/lib/core/urllib.test.js
test/lib/plugins/multipart.test.js
test/lib/plugins/watcher.test.js

test: fix unstable test

---

app/extend/context.js
app/extend/request.js
test/app/extend/context.test.js
test/fixtures/apps/demo/app/controller/ip.js
test/fixtures/apps/demo/app/router.js

closes https://github.com/eggjs/egg/issues/123

feat: add ip setter on request

---

lib/core/messenger.js
test/fixtures/apps/messenger-broadcast/agent.js
test/fixtures/apps/messenger-broadcast/app.js
test/fixtures/apps/messenger-broadcast/package.json
test/lib/agent.test.js
test/lib/core/agent_worker_client.test.js
test/lib/core/messenger.test.js

messenger
- broadcast is changed, it will send to all process
- send is changed, it won't emit message
Closes eggjs/egg#28

feat: [BREAKING_CHANGE] refactor Messenger

---

lib/agent.js
lib/core/messenger.js
test/fixtures/apps/messenger/agent.js
test/fixtures/apps/messenger/app.js
test/lib/core/messenger.test.js

messenger
Closes eggjs/egg#118

feat: warn when agent send message before started

---

config/config.default.js
lib/core/dnscache_httpclient.js
lib/core/urllib.js
test/fixtures/apps/dnscache_httpclient/app/controller/home.js
test/fixtures/apps/dnscache_httpclient/app/router.js
test/fixtures/apps/dnscache_httpclient/config/config.default.js
test/fixtures/apps/dnscache_httpclient/package.json
test/lib/core/dnscache_httpclient.test.js
test/lib/core/urllib.test.js
test/utils.js

Usage:
```js
// enable on urllib config
exports.urllib = {
enableDNSCache: true,
};
```

feat: add a dns cache httpclient

---

package.json
test/fixtures/apps/agent-app/app.js
test/fixtures/apps/agent-app/app/router.js
test/fixtures/apps/agent-app/plugins/mock-client/agent.js
test/fixtures/apps/agent-app/plugins/mock-client/app.js
test/fixtures/apps/agent-app/plugins/mock-client/mock_client.js
test/lib/core/agent_worker_client.test.js

close https://github.com/eggjs/egg/issues/130

test: refactor workclient test cases

---

app/middleware/body_parser.js
config/config.default.js
package.json
test/app/middleware/body_parser.test.js
test/fixtures/apps/body_parser_testapp_disable/app/router.js
test/fixtures/apps/body_parser_testapp_disable/config/config.default.js
test/fixtures/apps/body_parser_testapp_disable/package.json
test/fixtures/apps/body_parser_testapp_ignore/app/router.js
test/fixtures/apps/body_parser_testapp_ignore/config/config.default.js
test/fixtures/apps/body_parser_testapp_ignore/package.json
test/fixtures/apps/body_parser_testapp_match/app/router.js
test/fixtures/apps/body_parser_testapp_match/config/config.default.js
test/fixtures/apps/body_parser_testapp_match/package.json

feat: body parser support disable, ignore and match

---

app/middleware/body_parser.js
package.json

fix: already supported in egg-core

---

app/extend/request.js
test/app/extend/request.test.js

fix: protocolHeaders can split with whitespace

---

lib/core/agent_worker_client.js
lib/core/app_worker_client.js

refactor: use sendToApp/sendToAgent in worker client

---

config/config.default.js

refactor(config): set keepAliveTimeout 4000ms by default

---

docs/source/zh-cn/basics/env.md

doc
env
https://github.com/eggjs/egg/issues/34

doc: add basics/env.md

---

docs/source/zh-cn/basics/config.md

doc
config
https://github.com/eggjs/egg/issues/34

docs: add basics/config.md

---

docs/source/zh-cn/basics/schedule.md

docs: add schedule

---

docs/source/zh-cn/core/error-handling.md

docs: add error handling

---

app/extend/context.js
config/config.default.js
docs/source/zh-cn/core/httpclient.md
lib/core/context_httpclient.js
lib/core/httpclient.js
lib/egg.js
package.json
test/app/extend/application.test.js
test/app/extend/context.test.js
test/fixtures/apps/context_httpclient/package.json
test/fixtures/apps/dnscache_httpclient/config/config.default.js
test/lib/core/context_httpclient.test.js
test/lib/core/dnscache_httpclient.test.js
test/lib/core/httpclient.test.js

docs: core/httpclient.md

---

docs/source/zh-cn/core/i18n.md

docs: add core/i18n.md

---

docs/source/zh-cn/core/i18n.md

docs: fix i18n doc

---

docs/source/zh-cn/basics/router.md

docs: add basics/router.md

---

docs/source/zh-cn/advanced/cluster.md

docs: mv cluster.md to zh-cn

---

docs/source/zh-cn/core/security.md

docs: add security plugin doc

---

docs/source/zh-cn/guide/quickstart.md

docs: quickstart

---

docs/source/zh-cn/advanced/cluster.md
docs/source/zh-cn/advanced/loader.md
docs/source/zh-cn/basics/app-start.md
docs/source/zh-cn/basics/extend.md
docs/source/zh-cn/basics/schedule.md
docs/source/zh-cn/core/httpclient.md
docs/source/zh-cn/core/logger.md

docs: remove init.js from document, use app.beforeStart

---

docs/source/advanced/write_plugin.md
docs/source/zh-cn/advanced/cluster.md
docs/source/zh-cn/advanced/plugin.md

doc: add plugin doc

---

lib/egg.js
test/lib/application.test.js

app.env 和 app.proxy 代理到 app.config 上的配置，并加上 depreacate 信息。

feat: delegate configurations in app

---

docs/source/en-us/basics/env.md
docs/source/zh-cn/advanced/loader.md
docs/source/zh-cn/basics/config.md
docs/source/zh-cn/basics/env.md
docs/source/zh-cn/basics/schedule.md
docs/source/zh-cn/core/development.md
docs/source/zh-cn/core/error-handling.md
docs/source/zh-cn/core/logger.md
test/lib/cluster/master.test.js

docs: serverEnv => env

---

docs/source/zh-cn/core/development.md
docs/source/zh-cn/core/httpclient.md
docs/source/zh-cn/core/unittest.md

docs: add core/unittest.md

---

app/extend/context.js
app/extend/response.js

`ctx.jsonp === ctx.response.jsonp`
closes #184

feat: delegate ctx.jsonp to ctx.response.jsonp

---

app/extend/context.js
app/extend/request.js
app/extend/response.js
test/app/extend/context.test.js
test/app/extend/response.test.js

closes https://github.com/eggjs/egg/issues/185

refactor: ctx.realStatus delegate ctx.response.realStatus

---

docs/_config.yml

docs: set the default locale zh-cn

---

.travis.yml
CONTRIBUTING.md
CONTRIBUTING.zh-CN.md
README.md
README.zh-CN.md
appveyor.yml
docs/source/zh-cn/core/view.md
package.json

docs: contributing && readme

---

app/extend/context.js
lib/core/context_httpclient.js

fix: typo conext -> context

---

docs/source/_data/guide_toc.yml
docs/source/zh-cn/intro/egg-and-koa.md
docs/source/zh-cn/tutorials/progressive.md
docs/themes/egg/languages/zh-cn.yml

- 增加`渐进式开发`的文档
- 对应的 example: https://github.com/eggjs/examples/pull/10

docs: add progressive usage

---

docs/source/zh-cn/advanced/plugin.md
docs/source/zh-cn/intro/quickstart.md

docs: adjust some words

---

test/fixtures/apps/encrypt-cookies/config/plugin.js
test/fixtures/apps/secure-app/config/plugin.js
test/lib/core/cookies.test.js
test/lib/plugins/security.test.js

test: fix security test cases

---

app/extend/context.js
app/extend/request.js
test/app/extend/context.test.js
test/app/extend/request.test.js

`context.isAjax`, `request.isAjax`
- remove `request.isAjax`
- remove `ctx.roleFailureHandler`
closes #186

feat: remove isAjax

---

docs/source/zh-cn/advanced/cluster.md

chore(doc): fix typo $app to app

---

app/extend/response.js
config/plugin.js
package.json
test/fixtures/apps/demo/app/router.js
test/fixtures/apps/secure-app/app/controller/index.js
test/fixtures/apps/secure-app/app/router.js
test/lib/core/loader/load_plugin.test.js

Closes https://github.com/eggjs/egg/issues/288

refactor: remove ctx.jsonp and add egg-jsonp plugin

---

app/extend/request.js
package.json

style: fix code style for app and config

---

docs/source/zh-cn/core/security.md

docs: add more details about csrf

---

docs/source/zh-cn/basics/controller.md

docs: controller support class and refactor jsonp

---

README.md
README.zh-CN.md
docs/themes/egg/layout/index.swig

docs: plugin and framework list use github tags

---

lib/egg.js
test/fixtures/apps/cluster_mod_app/lib/registry_client.js
test/lib/cluster/cluster-client.test.js

feat: close clust clients before close

---

docs/source/en/intro/quickstart.md
docs/source/zh-cn/intro/quickstart.md

docs: fix quickstart example code

---

scripts/doc.js

scripts
https://github.com/eggjs/egg/blob/85e3c8f97f3990bad8ebfe890eac15cdfa0c3cbc/scripts/doc.sh#L3

chore(scripts): Add PATH to find hexo

---

docs/source/en/intro/quickstart.md
docs/source/zh-cn/basics/controller.md
docs/source/zh-cn/intro/quickstart.md

- close https://github.com/eggjs/egg/issues/290
- releate: https://github.com/eggjs/examples/pull/13

docs: quickstart - use controller class

---

lib/egg.js

fix: remove tair and hsf

---

docs/source/zh-cn/intro/egg-and-koa.md

docs: update egg-and-koa with async function

---

test/fixtures/apps/demo/app/controller/foo.js
test/fixtures/apps/demo/app/router.js
test/lib/application.test.js

test: add class style controller tests

---

docs/source/zh-cn/advanced/cluster.md

doc: add APIClient concept to cluster doc

---

docs/source/_data/menu.yml
docs/themes/egg/languages/en.yml
docs/themes/egg/languages/zh-cn.yml
docs/themes/egg/layout/index.swig
docs/themes/egg/layout/layout.swig
docs/themes/egg/layout/page.swig
docs/themes/egg/layout/partial/aside.swig
docs/themes/egg/layout/partial/footer.swig
docs/themes/egg/layout/partial/head.swig
docs/themes/egg/layout/partial/header.swig
docs/themes/egg/layout/plugins.swig
docs/themes/egg/layout/release.swig
docs/themes/egg/scripts/helpers.js
docs/themes/egg/source/css/page/index.less
docs/themes/egg/source/css/page/page.less
docs/themes/egg/source/css/partial/footer.less
docs/themes/egg/source/css/partial/main.less
docs/themes/egg/source/css/partial/mobile.less
docs/themes/egg/source/css/partial/nav.less
docs/themes/egg/source/css/partial/toc.less
docs/themes/egg/source/css/partial/var.less
docs/themes/egg/source/css/vendor/github-markdown.less
docs/themes/egg/source/css/vendor/highlight-github.less

- 1.  重新设计并修改官网的风格
- 2. 增加中英文切换
- 3. 调整移动端的适配
- 4. 修改英文版本部分文案
- 5. 修改 markdown 解析后文字样，包括调整字间距，行距，代码风格，表格样式，标题样式。

docs: update site style 

---

docs/themes/egg/layout/index.swig

docs: typo Github > GitHub

---

docs/source/zh-cn/tutorials/async-function.md

doc: fix async link

---

README.md
docs/source/plugins/index.md
docs/source/zh-cn/intro/index.md

docs: english wip description & remove unuse file

---

docs/source/zh-cn/basics/config.md

docs: add config result description

---

.gitignore
docs/themes/egg/layout/partial/footer.swig
package.json
scripts/doc.js

docs: update version automatically

---

docs/source/_data/guide_toc.yml
docs/source/zh-cn/advanced/plugin.md
docs/source/zh-cn/resource.md

docs: add plugin dep name description

---

docs/source/zh-cn/basics/config.md

docs: fix filename in config.md

---

lib/agent.js
lib/application.js
lib/egg.js
test/fixtures/apps/dumpconfig-app/app.js
test/fixtures/apps/dumpconfig/app.js
test/fixtures/apps/dumpconfig/config/config.default.js
test/fixtures/apps/dumpconfig/package.json
test/lib/egg.test.js

feat: dump config both after loaded and ready

---

docs/source/zh-cn/basics/middleware.md

docs
how to use koa's middleware

docs: how to use koa's middleware

---

docs/source/_data/guide_toc.yml
docs/source/en/intro/quickstart.md
docs/source/zh-cn/advanced/plugin.md
docs/source/zh-cn/basics/structure.md
docs/source/zh-cn/intro/quickstart.md
docs/themes/egg/languages/en.yml
docs/themes/egg/languages/zh-cn.yml

docs: add directory structure

---

docs/source/zh-cn/basics/middleware.md
docs/source/zh-cn/intro/egg-and-koa.md

docs: use compress replace bodyparser for example

---

lib/egg.js
test/fixtures/apps/app-throw/app/router.js
test/lib/egg.test.js

fix: keep unhandledRejectionError err object stack

---

docs/source/en/faq.md
docs/source/zh-cn/faq.md

docs: add csrf to faq

---

CONTRIBUTING.md
CONTRIBUTING.zh-CN.md

docs: fix character type error and link reference error

---

README.md

docs: correct english description at README

---

docs/source/zh-cn/advanced/cluster.md
test/lib/core/messenger.test.js

docs: should listen egg-ready using messenger

---

docs/source/en/intro/quickstart.md
docs/source/zh-cn/intro/quickstart.md

close https://github.com/eggjs/egg/issues/410

docs: add more complete example code for quickstart

---

docs/source/zh-cn/tutorials/mysql.md

docs: 更正文档教程版本号，使用最新版本egg-mysql

---

app/extend/context.js
test/lib/core/cookies.test.js

feat: log error when cookie value's length exceed the limit

---

lib/application.js
lib/egg.js
test/fixtures/apps/cluster-client-error/app.js
test/fixtures/apps/cluster-client-error/package.json
test/lib/cluster/cluster-client-error.test.js
test/lib/cluster/cluster-client.test.js

fix: close gracefully

---

app/extend/context.js
lib/application.js
test/async/index.test.js

cookie
related: https://github.com/eggjs/egg-cookies/pull/5

fix: listen CookieLimitExceed in app

---

LICENSE
docs/source/zh-cn/tutorials/mysql.md

docs: add year to licence && mysql docs

---

docs/source/zh-cn/tutorials/async-function.md

一个完整的例子可以参考 [examples/hackernews-async](https://github.com/eggjs/examples/tree/async-await/hackernews-async)。
to
一个完整的例子可以参考 [examples/hackernews-async](https://github.com/eggjs/examples/tree/master/hackernews-async)。

docs: fix async-function demo URL 404

---

test/app/extend/agent.test.js
test/app/extend/application.test.js
test/fixtures/apps/agent-throw/config/config.unittest.js
test/fixtures/apps/app-start-timeout/config/config.unittest.js
test/fixtures/apps/app-throw/config/config.unittest.js
test/fixtures/apps/csrf-enable/config/config.unittest.js
test/fixtures/apps/csrf-ignore/config/config.unittest.js
test/fixtures/apps/ctx-background/config/config.unittest.js
test/fixtures/apps/dnscache_httpclient/config/config.unittest.js
test/fixtures/apps/logger/config/config.unittest.js
test/fixtures/apps/mock-production-app/config/config.unittest.js
test/fixtures/apps/multiple-view-engine/config/config.unittest.js
test/fixtures/apps/onerror/config/config.unittest.js
test/fixtures/apps/secure-app/config/config.unittest.js
test/fixtures/apps/validate_form/config/config.unittest.js
test/lib/cluster/master.test.js
test/lib/core/httpclient.test.js
test/lib/core/logger.test.js
test/lib/core/messenger.test.js
test/lib/core/view.test.js

test: disable error log to stderr

---

docs/source/zh-cn/advanced/cluster.md

fixed spelling mistake

---

.travis.yml

test: travis test on node 8 using nightly building

---

docs/source/_data/guide_toc.yml
docs/source/en/basics/env.md
docs/source/zh-cn/advanced/deployment.md
docs/source/zh-cn/basics/env.md
docs/source/zh-cn/core/deployment.md
docs/themes/egg/languages/zh-cn.yml

docs: add document for deployment

---

docs/source/_data/guide_toc.yml

docs: fix deployment link

---

docs/source/en/faq.md
docs/source/zh-cn/faq.md

docs: add config merge to faq

---

docs/source/zh-cn/intro/egg-and-koa.md

docs: remove meaningless word

---

docs/source/en/intro/quickstart.md
docs/source/zh-cn/intro/quickstart.md

doc: add the view config for the egg-view-nunjucks

---

docs/source/en/intro/quickstart.md
docs/source/zh-cn/intro/quickstart.md

docs: quickstart tip

---

docs/source/en/intro/quickstart.md
docs/source/zh-cn/intro/quickstart.md

Fix html closing tag of a template sample(`app/view/news/list.tpl`) in quickstart document.

docs(quickstart): fix html closing tag

---

docs/source/_data/guide_toc.yml
docs/source/zh-cn/basics/controller.md
docs/source/zh-cn/core/cookie-and-session.md
docs/themes/egg/languages/en.yml
docs/themes/egg/languages/zh-cn.yml

docs: add cookie and session

---

docs/source/en/intro/quickstart.md
docs/source/zh-cn/intro/quickstart.md

https://github.com/eggjs/egg/pull/511#issuecomment-284221305

docs(quickstart): fix keys again

---

docs/source/zh-cn/basics/middleware.md

docs: fix middleware typo

---

docs/source/zh-cn/core/cookie-and-session.md
docs/themes/egg/lib/renderer.js

It's affected by
https://github.com/medfreeman/markdown-it-toc-and-anchor/commit/3eb39de83686fbb79f6a2197ef7737104470f289

docs: fix doc build

---

test/lib/plugins/development.test.js

test: fix development test

---

docs/themes/egg/source/css/partial/toc.less

fix: docs scroll

---

docs/source/zh-cn/advanced/loader.md
docs/source/zh-cn/core/cookie-and-session.md

docs: rule for transforming filepath to properties

---

docs/source/zh-cn/basics/schedule.md

docs: fix typo

---

docs/themes/egg/layout/partial/header.swig
docs/themes/egg/source/css/partial/nav.less

PS: sometime, the docsearch will got js error, had reported at https://github.com/algolia/docsearch/issues/171

docs: update the style for search

---

docs/source/en/basics/app-start.md
docs/source/zh-cn/advanced/plugin.md
docs/source/zh-cn/basics/app-start.md
docs/source/zh-cn/basics/controller.md
docs/source/zh-cn/basics/extend.md
docs/source/zh-cn/basics/service.md
docs/source/zh-cn/core/error-handling.md
docs/source/zh-cn/core/security.md
docs/source/zh-cn/tutorials/mysql.md
docs/source/zh-cn/tutorials/restful.md

close https://github.com/eggjs/egg/issues/566

docs: change controller showcase style to ctx

---

README.md
docs/source/en/intro/egg-and-koa.md
docs/source/zh-cn/basics/controller.md
docs/source/zh-cn/basics/router.md
docs/source/zh-cn/core/httpclient.md
docs/source/zh-cn/core/i18n.md
docs/source/zh-cn/core/unittest.md
docs/source/zh-cn/core/view.md
docs/source/zh-cn/intro/egg-and-koa.md
docs/source/zh-cn/tutorials/mysql.md
docs/source/zh-cn/tutorials/restful.md

- close https://github.com/eggjs/egg/issues/576
- close https://github.com/eggjs/egg/issues/572

docs: add gitter & more controller ctx style

---

docs/source/zh-cn/core/cookie-and-session.md

docs: fix session link

---

docs/source/zh-cn/core/cookie-and-session.md

docs: fix session's maxage

---

docs/source/zh-cn/core/security.md
scripts/doc.js

Ref https://github.com/eggjs/egg/issues/608

docs: fix document deploy

---

docs/source/zh-cn/tutorials/index.md
docs/themes/egg/layout/index.swig
docs/themes/egg/layout/partial/footer.swig
docs/themes/egg/layout/partial/header.swig
docs/themes/egg/source/css/partial/main.less
docs/themes/egg/source/css/partial/toc.less

docs: improve left padding when window between 1005 and 1130

---

docs/source/en/basics/env.md
docs/source/zh-cn/basics/env.md

Fixed table render error in environment document of English version.

doc: fix table render error in en env.md

---

docs/themes/egg/layout/layout.swig
docs/themes/egg/layout/partial/footer.swig

docs: move cnzz to layout

---

docs/source/zh-cn/tutorials/async-function.md

Change `async gzip(ctx, next)` to `async function gzip(ctx, next)`

docs: fix code syntax

---

docs/source/zh-cn/basics/middleware.md

Here, `this.body = zlib.createGzip().end(body);` Gzip object end method return undefined (test in Node v7.6.0), and `this.body` will be null. Here should assign Gzip Object to `this.body`, then execute end method.

docs: fix example code in basics/middleware

---

docs/source/zh-cn/core/view.md

- docs: fix some typo `路径` => `后缀`

docs: fix some typo

---

docs/source/zh-cn/core/cookie-and-session.md

change
```js
// plugin.js
exports.redis = {
enable: true,
package: 'egg-redis',
};
exports.sessionRedis = {
enable: true,
// **ATTENTION**
package: 'egg-redis-session',
};
```
to
```js
// plugin.js
exports.redis = {
enable: true,
package: 'egg-redis',
};
exports.sessionRedis = {
enable: true,
// **ATTENTION**
package: 'egg-session-redis',
};
```

docs: fix egg-session-redis example code

---

docs/source/zh-cn/basics/controller.md
docs/source/zh-cn/basics/middleware.md
docs/source/zh-cn/tutorials/restful.md

1. `app.resources('Topic', '/api/v2/topics', 'topics');` in RESTful tutorial, here the controller name should be `topic`;
2. `jsonLimit: '10m'` in middleware document, here the size should be `10mb`.
close https://github.com/eggjs/egg/issues/630

docs: fix example code typos

---

docs/source/zh-cn/basics/controller.md

* docs: fix example code syntax error & typos

docs: fix example code syntax error & typos

---

docs/source/zh-cn/tutorials/async-function.md

docs:correct spelling mistake

---

docs/source/zh-cn/core/development.md

- close https://github.com/eggjs/egg/issues/616

docs: add webstorm debug

---

config/config.default.js

chore: remove unused config

---

docs/source/zh-cn/tutorials/async-function.md

docs: change generator to async

docs: change generator to async

---

docs/source/zh-cn/basics/controller.md

将“字符数”改为“字节数”。因为Content-Length表示的是”字节数“。原文中的“字符数”不是很精确。

docs: typo at controller.md

---

docs/source/zh-cn/basics/controller.md
docs/source/zh-cn/basics/router.md

docs: add sub directory support for controller

---

app/extend/context.js

fix: remove unused jsonp delegate

---

.gitignore
History.md
docs/plugins.puml
lib/egg.js
package.json

Release 1.1.0

---

docs/source/zh-cn/advanced/framework.md

doc: fix typo, egg-bin => egg-init

---

app/extend/request.js
lib/loader/agent_worker_loader.js
lib/loader/app_worker_loader.js

chore: remove chinese commnets

---

docs/source/zh-cn/basics/middleware.md

Closes https://github.com/eggjs/egg/issues/723

docs: document for middleware order

---

README.md

docs: link plugins to github search results

---

docs/source/zh-cn/resource.md

close https://github.com/eggjs/egg/issues/583

docs: add vscode plugin link

---

docs/source/zh-cn/core/development.md

docs: add inspector protocol vscode debug

---

docs/source/zh-cn/basics/structure.md
docs/source/zh-cn/core/cookie-and-session.md
docs/source/zh-cn/core/httpclient.md
docs/source/zh-cn/core/security.md

1.在 `目录结构` 章节中，增加关于`agent.js`作用说明的链接。
2.对3个章节里几个错词及不恰当用词进行修改。

docs: Modify some words

---

docs/source/zh-cn/core/development.md

close https://github.com/eggjs/egg/issues/809

docs: only use inspect at 7.x+

---

docs/source/zh-cn/basics/router.md

close https://github.com/eggjs/egg/issues/830

docs: fix  wrong name in chinese router doc

---

History.md
package.json

Release 1.2.1

---

docs/package.json
docs/source/_data/menu.yml
docs/source/api/index.md
docs/themes/egg/scripts/helpers.js
scripts/doc.js

Ref https://github.com/eggjs/egg/issues/581

docs: Add API document to menu

---

README.md
README.zh-CN.md

feat: add quality badge

---

docs/source/zh-cn/core/view.md

docs: fix view typo

---

lib/core/singleton.js

fix: typo eggg=>egg

---

docs/source/zh-cn/basics/structure.md

`docs>source>zh-cn>basics->structure.md`
Agent link typo

docs(basics/structure.md): link agent typo

---

docs/source/zh-cn/basics/service.md

fix(docs):  yield db.query

---

docs/source/zh-cn/basics/controller.md

fix(docs): use names of constants declared

---

docs/source/zh-cn/basics/objects.md

docs: fix objects.md

---

docs/source/en/basics/service.md

'basics/service.md' is translated and waiting for being proofread.

docs(basics/service.md): [translate] Done.

---

docs/source/en/basics/service.md

fix(docs): yield db.query for en

---

docs/source/zh-cn/core/unittest.md

`docs/zh-cn/core/unittest.md`
Update document with latest `egg-mock` unit test.
* Remove `const request = require('supertest');` and `request(app.callback())` 
* Use `app.httpRequest()` instead. 
* Add some text descriptions.
Reference: https://github.com/eggjs/egg-mock/commit/318b6c2e2bc14e582b5646ebe3edb835a276d02b

docs(core/unittest.md): update with app.httpRequest()

---

docs/source/zh-cn/basics/objects.md

docs/source/zh-cn/basics/objects.md
fix typo

docs: Fix objects.md typo

---

config/config.default.js
docs/source/zh-cn/core/httpclient.md
lib/core/dnscache_httpclient.js
package.json
test/lib/core/dnscache_httpclient.test.js

feat: use lru to aovid oom in dns cache httpclient

---

docs/source/en/basics/controller.md
docs/source/zh-cn/basics/controller.md

docs: file must appear after other fiels when using getFileStream

---

test/lib/plugins/schedule.test.js

test: disable coverage for schedule

---

docs/source/zh-cn/core/development.md

https://github.com/eggjs/egg/issues/985

docs: devtool inspect at 8.x

---

docs/source/zh-cn/advanced/loader.md

docs: fix caseStyle link

---

package.json
test/app/extend/application.test.js
test/app/middleware/site_file.test.js
test/lib/cluster/app_worker.test.js
test/lib/cluster/cluster-client.test.js
test/lib/cluster/master.test.js
test/lib/core/messenger.test.js
test/lib/egg.test.js

increase mocha test timeout on coverage test

test: make sure app close

---

docs/source/en/intro/quickstart.md
docs/source/zh-cn/intro/quickstart.md
docs/source/zh-cn/tutorials/async-function.md

docs: add more description at quickstart

---

docs/source/zh-cn/core/development.md

-  [x]  `npm test` passes
-  [x]  documentation is changed or added
-  [x]  commit message follows commit guidelines
文档里面添加 chrome devtools 的调试用法

docs: add chrome devtools debug information

---

index.d.ts

tsd: add another properties of FileStream

---

docs/source/_data/links.yml

HTML-generation has been tested, and it works!

docs: add Enclose.IO to Links

---

config/config.default.js

chore: comments in english

---

docs/source/en/intro/index.md
docs/source/zh-cn/intro/index.md

docs: improve feature describe

---

index.d.ts

我不是十分确定body的类型，所以应该是any吧？毕竟可能为 object, string或array吧？

tsd: add propery 'body' in Request

---

index.d.ts
test/fixtures/apps/app-ts/app/controller/foo.ts

chore(tsd): add ctx.logger and logger.error support Error object

---

docs/source/zh-cn/basics/objects.md

内置对象章节缺少 class 关键字声明

---

docs/source/zh-cn/core/development.md

docs: change istanbul to nyc

---

History.md
package.json

Release 1.6.0

---

.travis.yml

chore: add travis_wait to avoid deploying document timeout

---

scripts/doc_travis.sh

chore: kill ssh-agent after deploy

---

docs/source/en/core/i18n.md

docs/source/en/core/i18n.md
Translated https://github.com/eggjs/egg/blob/master/docs/source/zh-cn/core/i18n.md, thanks for any comments and reviews

docs: (core/i18n): [translate] Done

---

History.md
package.json

Release 1.6.1

---

lib/core/dnscache_httpclient.js
lib/core/httpclient.js
lib/egg.js
test/fixtures/apps/httpclient-overwrite/app.js
test/fixtures/apps/httpclient-overwrite/config/config.default.js
test/fixtures/apps/httpclient-overwrite/package.json
test/lib/core/httpclient.test.js

refactor: export app.HttpClient that can be overwritten

---

docs/source/en/core/deployment.md

`docs/source/en/core/deployment.md`
translation

docs(core-deployment): translate deployment.md in English

---

.eslintignore
docs/source/zh-cn/core/cookie-and-session.md

https://cnodejs.org/topic/5979cdbe68aa87c774e5ecbb

docs: fix const define

---

.travis.yml

docs: only deploy docs at 8

---

History.md
package.json

Release 1.7.0

---

scripts/doc_travis.sh

https://docs.travis-ci.com/user/cron-jobs/#Detecting-Builds-Triggered-by-Cron

chore: skip docs deploy at ci cron

---

docs/source/zh-cn/core/unittest.md

docs(unittest): typo of egg-mock

---

docs/source/zh-cn/core/deployment.md

- https://github.com/eggjs/egg-scripts/pull/2

docs: remove egg-scripts env default description

---

docs/source/en/core/logger.md

docs/en/core/logger.md
Create translation in English

docs(core/logger): create logger.md in core

---

lib/egg.js

内置的 curl 方法增加 nestedQuerystring 入参说明，对 Post 请求更加友好

---

docs/source/zh-cn/core/development.md

https://github.com/eggjs/egg-bin/pull/71

docs: adjust webstorm debug config

---

lib/core/base_context_class.js

fix: should extends from egg-core BaseContextClass

---

docs/source/en/basics/objects.md

`docs/source/en/basics/objects.md`
translation

docs(basics/objects): translate

---

History.md
package.json

Release 1.8.0

---

docs/source/en/core/deployment.md
docs/source/zh-cn/core/deployment.md

https://github.com/eggjs/egg/commit/c1c7a0675e73ea0e934abfcbece710db14414760

docs(deployment): port should be number

---

docs/source/zh-cn/core/development.md
docs/source/zh-cn/resource.md

https://github.com/eggjs/egg/issues/1376

docs(development): adjust debug docs with new egg-bin debug

---

docs/source/zh-cn/core/development.md

docs(development): fix devtools debug

---

docs/source/zh-cn/advanced/plugin.md
test/lib/core/httpclient.test.js

close https://github.com/eggjs/egg/issues/1497

docs: add plugin.js description

---

docs/source/en/basics/controller.md
docs/source/zh-cn/basics/controller.md

docs: multipart example use yield parts()

---

docs/source/en/basics/middleware.md
docs/source/zh-cn/basics/middleware.md

close https://github.com/eggjs/egg/issues/1520

docs: adjust middleware config at framework

---

docs/source/zh-cn/basics/schedule.md

- https://github.com/eggjs/egg-schedule/pull/23

docs: adjust new schedule

---

docs/source/zh-cn/core/security.md

close https://github.com/eggjs/egg/issues/1547#issuecomment-337854033

docs: fix csrf

---

docs/source/en/core/deployment.md
docs/source/zh-cn/core/cluster-and-ipc.md
docs/source/zh-cn/core/deployment.md

close https://github.com/eggjs/egg/issues/593

docs: fix egg-scripts

---

.travis.yml

test: add node 9 and drop node 7

---

History.md

chore: fix 1.10.1 history.md

---

index.d.ts

export as global module, so user could:
```js
/**
* @param {Egg.Application} app - egg application
*/
module.exports = app => {
app.get('/', app.controller.home.index);
};
```

feat: export global namespace at d.ts

---

History.md
package.json

Release 1.11.0

---

History.md
package.json

Release 2.0.0-beta.1

---

docs/source/zh-cn/tutorials/async-function.md

docs: fix typo in async function

---

docs/source/en/basics/schedule.md
docs/source/zh-cn/basics/schedule.md

docs(schedule): generator -> async

---

History.md
package.json

Release 2.0.0-beta.2

---

docs/source/en/intro/quickstart.md
docs/source/zh-cn/intro/quickstart.md

close https://github.com/eggjs/egg/issues/1658

docs(quickstart): fix app.Service

---

app/extend/context.js
lib/application.js
lib/core/utils.js
test/lib/core/utils.test.js

fix: dump async function as AsyncFunction

---

docs/source/en/intro/egg-and-koa.md
docs/source/zh-cn/intro/egg-and-koa.md

docs: refine egg-and-koa with egg 2

---

History.md
README.md
package.json

Release 2.0.0

---

package.json
test/lib/core/loader/load_plugin.test.js

chore: set publishConfig.tag to release-1.x

---

docs/source/zh-cn/basics/schedule.md

docs: fixed some typo.

---

docs/source/zh-cn/migration.md

docs(migration): remove Promise.props()

---

docs/source/en/basics/objects.md
docs/source/zh-cn/basics/objects.md

docs(objects): use async

---

docs/source/en/basics/service.md
docs/source/zh-cn/basics/service.md

docs(service): use async

---

docs/source/en/basics/controller.md
docs/source/zh-cn/basics/controller.md

docs(controller): use async

---

docs/source/en/tutorials/mysql.md
docs/source/zh-cn/tutorials/mysql.md

docs(mysql): use async

---

app/extend/context.js
docs/source/en/core/unittest.md
docs/source/zh-cn/core/unittest.md
index.d.ts
lib/egg.js

docs(unittest): use async

---

docs/source/zh-cn/advanced/view-plugin.md
docs/source/zh-cn/core/view.md

docs(view): use async

---

docs/source/en/core/logger.md
docs/source/zh-cn/core/logger.md

docs(logger): use async

---

docs/source/en/core/error-handling.md
docs/source/zh-cn/core/error-handling.md

docs(error-handling): use async

---

docs/source/en/intro/quickstart.md
docs/source/en/tutorials/restful.md
docs/source/zh-cn/intro/quickstart.md
docs/source/zh-cn/tutorials/index.md
docs/source/zh-cn/tutorials/restful.md

docs(restful): use async

---

docs/source/en/core/httpclient.md
docs/source/zh-cn/core/httpclient.md

docs(httpclient): use async

---

lib/application.js
lib/egg.js
package.json
test/fixtures/apps/base-context-class/config/config.unittest.js
test/fixtures/apps/demo/app.js
test/fixtures/apps/demo/app/controller/obj.js
test/fixtures/apps/demo/app/controller/obj2.js
test/fixtures/apps/demo/app/router.js
test/fixtures/apps/demo/config/config.default.js
test/lib/core/httpclient.test.js
test/lib/egg.test.js

Demo of router.json https://gist.github.com/fengmk2/7f7df8c33cf36b8685a3196ca50656a8

feat: dump application router json

---

lib/application.js
lib/egg.js
package.json
test/fixtures/apps/base-context-class/config/config.unittest.js
test/fixtures/apps/demo/app.js
test/fixtures/apps/demo/app/controller/obj.js
test/fixtures/apps/demo/app/controller/obj2.js
test/fixtures/apps/demo/app/router.js
test/fixtures/apps/demo/config/config.default.js
test/lib/core/httpclient.test.js
test/lib/egg.test.js

pick from https://github.com/eggjs/egg/pull/1712

Router json for 2.x

---

docs/source/en/core/cluster-and-ipc.md
docs/source/zh-cn/core/cluster-and-ipc.md

docs(ipc): use async

---

docs/source/zh-cn/advanced/cluster-client.md

docs(cluster-client): use async

---

docs/source/zh-cn/advanced/framework.md

docs(framework): use new way

---

docs/source/zh-cn/advanced/plugin.md

docs(plugin): use async

---

docs/source/en/core/cookie-and-session.md
docs/source/zh-cn/core/cookie-and-session.md

docs(cookie-session): use async

---

docs/source/zh-cn/intro/quickstart.md

docs(quickstart): fix typo in code example

---

docs/source/zh-cn/migration.md

https://github.com/eggjs/egg/issues/1564#issuecomment-346542460

docs(migration): add description for plugin breakchange

---

docs/source/en/tutorials/progressive.md

docs(progressive):changes some grammar

---

docs/source/zh-cn/advanced/loader.md

docs(loader): adjust extends way

---

docs/source/en/basics/middleware.md
docs/source/zh-cn/basics/middleware.md

close https://github.com/eggjs/egg/issues/1804

docs(middleware): add description of import koa middleware

---

docs/source/_data/links.yml

docs: add AntV links

---

docs/source/_data/guide_toc.yml
docs/source/languages/en.yml
docs/source/languages/th.yml
docs/source/languages/zh-cn.yml
docs/source/zh-cn/tutorials/passport.md

docs(passport): the missing docs for passport

---

docs/source/zh-cn/tutorials/passport.md

docs(passport): fix some description

---

History.md
package.json

Release 2.1.0

---

.gitignore
lib/application.js
test/lib/cluster/app_worker.test.js

server
backport to 1.x of https://github.com/eggjs/egg/pull/1829

feat: add 400 response for broken client request to instead of empty response

---

docs/source/en/core/error-handling.md
docs/source/zh-cn/core/error-handling.md

docs(error-handling):fix some words

---

docs/source/en/basics/objects.md

docs(objects):fix some grammars

---

app/middleware/meta.js
config/config.default.js
test/app/middleware/meta.test.js
test/fixtures/apps/meta-logging-app/app.js
test/fixtures/apps/meta-logging-app/app/controller/home.js
test/fixtures/apps/meta-logging-app/app/router.js
test/fixtures/apps/meta-logging-app/config/config.default.js
test/fixtures/apps/meta-logging-app/package.json

feat: enable request started log on meta middleware

---

History.md
package.json

Release 2.2.0

---

docs/source/en/core/deployment.md
docs/source/en/index.md
docs/source/zh-cn/core/deployment.md

docs(deploy): add --ignore-stderr

---

docs/source/_data/links.yml

docs
Add link to alicloud node.js perfomance platform

docs(links): Add link to alicloud node.js perfomance platform

---

docs/source/en/basics/objects.md

docs(basic-objects): fix some descriptions

---

docs/source/languages/en.yml

English document index
Add missing field to fix messy code in http://eggjs.org/en/intro/index.html

docs(en-index): add missing field 

---

docs/source/en/core/cluster-and-ipc.md
docs/source/zh-cn/core/cluster-and-ipc.md

docs: fix word error

---

index.d.ts

fix(ts): error declare of route.resource

---

docs/_config.yml

https://github.com/eggjs/doctools/pull/30

docs: add deer stat

---

app/extend/helper.js
index.d.ts

feat: add helper interface in d.ts

---

lib/application.js
test/lib/application.test.js

fix: log cookie's key when cookie exceed limit length

---

docs/source/en/core/unittest.md
docs/source/zh-cn/core/unittest.md

docs(core/unittest): fix path of helper.js(#2029)

---

lib/application.js
package.json
test/lib/application.test.js

feat: add request and response event

---

docs/source/en/advanced/cluster-client.md

I would like to translate advanced/cluster-client.md, please assgin it to me, thanks.

docs: translate advanced/cluster-client.md

---

History.md
package.json

Release 2.3.0

---

docs/source/en/advanced/loader.md
docs/source/zh-cn/advanced/loader.md

`docs/source/en/advanced/loader.md`
tranlation

docs(advanced/loader): translate

---

app/extend/request.js

Make some Chinese comments to English globally.
No functions changed

style(app/extend/request.js): Some Comments from Chinese To English in union

---

docs/source/en/basics/controller.md

- fix some description of basic-controller

docs(2.x-basic-controller):fix some descriptions of basic-controller

---

docs/source/zh-cn/core/development.md

- vscode 内置了多进程调试支持，https://code.visualstudio.com/updates/v1_20#_node-debugging

docs(development): adjust to new version vscode

---

docs/source/en/core/httpclient.md
docs/source/zh-cn/basics/plugin.md
docs/source/zh-cn/core/httpclient.md

https://github.com/eggjs/egg-core/pull/153#issuecomment-364315091

docs(plugin): add description for plugin.local.js

---

docs/source/en/basics/service.md

docs(2.x-basic-service):fix some mistakes of service

---

docs/source/en/basics/extend.md

docs(extend): fix some mistakes

---

docs/source/en/advanced/plugin.md

- [ x] documentation is changed or added
英文翻译 docs/source/en/advanced/plugin.md

docs: translation for advanced/plugin.md

---

docs/source/en/advanced/plugin.md
docs/source/zh-cn/advanced/plugin.md

docs(2.x-advanced-plugin):fix some descriptions

---

index.d.ts
package.json

install dependency '@types/urllib' to update curl
options types for better coding experience
update typings
Hello, I'm back again! This time `@types/urllib` is installed to add `curl options` declaration support in index.d.ts. Btw npm dependencies is updated.

perf: add curl options declaration support in index.d.ts

---

docs/source/en/core/unittest.md
docs/source/zh-cn/core/unittest.md

- fix word spelling of Chinese version
- fix some descriptions of English version

docs(unittest):fix some mistakes

---

docs/source/en/basics/schedule.md
docs/source/zh-cn/basics/schedule.md

docs(schedule): fix log dir

---

docs/source/en/basics/app-start.md
docs/source/zh-cn/basics/app-start.md

docs(app-start): how to call service

---

index.d.ts

fixed issue：https://github.com/eggjs/egg/issues/2148

fix: add logger in base_context_class

---

History.md
package.json

Release 2.4.0

---

index.d.ts

docs(d.ts): fix type of `render`

---

docs/source/en/intro/quickstart.md
docs/source/zh-cn/intro/quickstart.md

- ~~`npm test` passes~~
- ~~tests and/or benchmarks are included~~
No
**Before**
```html
<div class="news-view view">
{% for item in list %}
<div class="item">
<a href="{{ item.url }}">{{ item.title }}</a>
</div>
{% endfor %}
</div>
```
**After**
```html
<ul class="news-view view">
{% for item in list %}
<li class="item">
<a href="{{ item.url }}">{{ item.title }}</a>
</li>
{% endfor %}
</ul>
```
Also, added the `moment installation` step.

doc(quickstart): more semantic and moment installation

---

index.d.ts

add regexp as type of path
https://github.com/alexmingoia/koa-router/blob/master/lib/router.js#L194

fix(typings): add regexp as type of path

---

History.md
package.json

Release 1.13.1

---

History.md
package.json

Release 2.4.1

---

.autod.conf.js

chore: fix typo.

---

docs/source/en/basics/router.md
docs/source/zh-cn/basics/router.md
docs/source/zh-cn/tutorials/socketio.md

- close https://github.com/eggjs/egg/issues/2153
- close https://github.com/eggjs/egg/issues/2196

docs(socket.io): add webchat description

---

docs/source/zh-cn/tutorials/passport.md

docs: egg-passsport-local -> egg-passport-local

---

index.d.ts
test/fixtures/apps/app-ts/app/controller/foo.ts
test/fixtures/apps/app-ts/app/proxy/foo.d.ts

feat: tsd add init module

---

config/plugin.js

fix: spelling error rotator

---

package.json

chore: update package.json for release

---

docs/source/en/core/security.md
docs/source/zh-cn/core/security.md

https://github.com/eggjs/egg-security/pull/32
https://github.com/eggjs/egg-security/pull/33

docs(security): add ssrf in security

---

docs/source/en/resource.md

Added en translation for resources doc  #363

EN translation for resources doc

---

docs/source/en/basics/controller.md
docs/source/zh-cn/basics/controller.md

docs(controller): session example bug

---

History.md
package.json

Notable changes
* **feature**
* TypeScript tool support (#2272)
* **docs**
* improve d.ts with ts support (#2306)
* improve docs

Release 2.6.0

---

index.d.ts

fix(d.ts): add modifier to plugin and add middleware to config

---

index.d.ts

chore(typings): export PowerPartial

---

index.d.ts

chore(typings): add export to declarations

---

docs/source/en/core/cookie-and-session.md
docs/source/zh-cn/core/cookie-and-session.md

docs: intro session.renew in the doc

---

History.md

Release 2.6.1

---

docs/source/en/basics/router.md
docs/source/zh-cn/basics/router.md
docs/source/zh-cn/tutorials/typescript.md

docs: chore for router and typescript

---

README.md
README.zh-CN.md

docs: change English document on Readme

---

lib/egg.js
package.json
test/fixtures/apps/dumpconfig-circular/app.js
test/fixtures/apps/dumpconfig-circular/config/config.default.js
test/fixtures/apps/dumpconfig-circular/package.json
test/lib/egg.test.js

fix: dumpConfig support circular json

---

History.md
package.json

Release 1.13.2

---

History.md
package.json

Release 2.7.0

---

lib/core/singleton.js
lib/egg.js
test/fixtures/apps/singleton-demo/config/config.default.js
test/lib/core/singleton.test.js

fix: imporve compatibility of singleton

---

History.md
package.json

Release 2.7.1

---

.vscode/settings.json
docs/source/languages/en.yml

chore: update title and remove unused files

---

docs/source/en/core/view.md
docs/source/zh-cn/core/view.md

in the code of "locals", the key of value "egg" should be "name".

docs: fix the code error of LOCALS in view.md

---

config/config.default.js
lib/agent.js
lib/application.js
lib/egg.js
test/lib/cluster/app_worker.test.js
test/lib/egg.test.js

feat: add time duration for dump config

---

lib/core/singleton.js
test/lib/core/singleton.test.js

Fix prevent extensions

---

History.md
package.json

Release 2.8.0

---

config/config.default.js
lib/agent.js
lib/application.js
lib/egg.js
package.json
test/lib/egg.test.js

feat: add time duration for dump config (#2485)

---

index.d.ts

feat(d.ts): add runSchedule & Subscription define

---

lib/egg.js
test/lib/egg.test.js

https://github.com/eggjs/egg/issues/1898

feat: dump timing data for loader

---

History.md
package.json

Release 1.15.0

---

docs/source/en/core/cookie-and-session.md
docs/source/zh-cn/core/cookie-and-session.md

docs(cookie): how to get frontend cookie

---

config/config.default.js
lib/core/logger.js
test/fixtures/apps/mock-production-app-do-not-force/config/config.js
test/lib/core/logger.test.js

Make allowDebugAtProd configuration works as it is named.
Fix issue: https://github.com/eggjs/egg/issues/2310
Since nowhere mentioned this, no document needs to be updated.

Fixed allowDebugAtProd

---

index.d.ts

add d.ts for bodyparser

---

docs/source/en/intro/quickstart.md

move app.Service to Service
close #2574

docs: fix quickstart typo error

---

docs/source/en/advanced/plugin.md
docs/source/zh-cn/advanced/plugin.md

docs: tweek doc style

---

docs/source/en/core/logger.md
docs/source/zh-cn/core/logger.md

Closes https://github.com/eggjs/egg/issues/2555

docs(logger): the unit of maxFileSize should be byte

---

lib/egg.js
test/lib/egg.test.js

Ref https://github.com/eggjs/egg/issues/1898

feat: dump timing data for loader (#2521)

---

index.d.ts

Refs: https://github.com/eggjs/egg/pull/2650

[backport-1.x] fix: add key any to Context

---

History.md

Release 2.9.0

---

History.md
package.json

Release 1.15.1

---

docs/source/en/tutorials/socketio.md
docs/source/zh-cn/tutorials/socketio.md

https://github.com/eggjs/egg/issues/2601

docs: fix socketio's browser demo

---

docs/source/_data/links.yml

docs: add http://www.sofastack.tech

---

docs/source/en/basics/schedule.md
docs/source/zh-cn/basics/schedule.md

https://github.com/eggjs/egg-schedule/pull/39
https://github.com/eggjs/egg/issues/2725

docs(schedule): add env description

---

docs/source/en/basics/plugin.md
docs/source/zh-cn/basics/plugin.md

docs(plugin): add details for plugin.js

---

docs/source/en/core/logger.md
docs/source/zh-cn/core/logger.md

docs: add allowDebugAtProd in document

---

docs/source/en/core/cookie-and-session.md
docs/source/zh-cn/core/cookie-and-session.md

Example code of modify session value
Closes [#2819](https://github.com/eggjs/egg/issues/2819)

docs(session): fix bug in example code of modify session value

---

app/extend/context.js
package.json

see https://github.com/eggjs/egg-mock/pull/78

feat: allow runInBackground reuse on plugins

---

docs/source/en/core/deployment.md
docs/source/zh-cn/core/deployment.md

docs of deployment
1. fix typo, `type` => `title`
2. escape `--` in shell
Closes [#2896](https://github.com/eggjs/egg/issues/2896)

docs(deployment): fix typo

---

docs/source/_data/guide_toc.yml
docs/source/en/tutorials/sequelize.md
docs/source/zh-cn/tutorials/sequelize.md

基于 sequelize 的最佳实践，egg-sequelize + sequelize-cli + factory-girl。

docs: add sequelize

---

docs/source/en/tutorials/sequelize.md
docs/source/zh-cn/tutorials/sequelize.md

docs: fix sequelize link

---

CONTRIBUTING.md

docs: fix link to angular commit-message-format

---

docs/source/en/advanced/framework.md

None.
Fixed typo of Princeple to Principle

Fixed typo.

---

app/extend/context.js
config/config.default.js
lib/core/logger.js
package.json
test/app/extend/application.test.js
test/app/middleware/site_file.test.js
test/doc.test.js
test/fixtures/apps/mock-production-app-do-not-force/config/config.js
test/lib/core/loader/load_plugin.test.js
test/lib/core/logger.test.js

backport:
- https://github.com/eggjs/egg/pull/2469
- https://github.com/eggjs/egg/pull/2872
- https://github.com/eggjs/egg/pull/2940

feat: backport #2469 #2872 #2940

---

docs/source/en/intro/egg-and-koa.md
docs/source/en/intro/quickstart.md

fix 2 typos

---

History.md
package.json

Release 1.10.0

---

.travis.yml
appveyor.yml
config/config.default.js
lib/core/logger.js
package.json
test/app/middleware/site_file.test.js
test/fixtures/apps/mock-production-app-do-not-force/config/config.js
test/lib/core/cookies.test.js
test/lib/core/loader/load_plugin.test.js
test/lib/core/logger.test.js
test/lib/egg.test.js

pick https://github.com/eggjs/egg/pull/2469

fix: config.allowDebugAtProd default to false

---

History.md
package.json

Release 1.16.1

---

lib/core/dnscache_httpclient.js
test/lib/core/dnscache_httpclient.test.js

Closes https://github.com/eggjs/egg/issues/3001

fix(httpclient): can't use runInBackground in agent

---

History.md
package.json

Release 2.11.1

---

History.md
package.json

Release 2.11.2

---

docs/assets/lifecycle_cn.puml
docs/assets/lifecycle_en.puml
docs/source/en/advanced/loader.md
docs/source/zh-cn/advanced/loader.md
lib/loader/agent_worker_loader.js
lib/loader/app_worker_loader.js
package.json
test/lib/egg.test.js

 Refactor app config did load

---

History.md
package.json

Release 1.16.2

---

History.md
package.json

Release 2.12.0

---

History.md

fix(docs): Grammar of "lots of"

---

docs/assets/lifecycle_cn.puml
docs/assets/lifecycle_en.puml
docs/source/en/advanced/loader.md
docs/source/zh-cn/advanced/loader.md

Ref: https://github.com/eggjs/egg/pull/3101.
See comments in the end and fix the wrong explainations.

doc: Update the `configWillLoad` explainations

---

docs/source/en/tutorials/typescript.md
docs/source/zh-cn/tutorials/typescript.md
index.d.ts
test/fixtures/apps/app-ts/app.ts
test/ts/index.test.js

typings
add `IBoot` definition

chore(typings): add interface IBoot

---

.travis.yml
docs/source/_data/promotion.yml

docs: add promo logo

---

lib/core/utils.js

Use is.string() in utils.js for consistency

style: use is.string() in utils.js for consistency

---

docs/source/en/basics/plugin.md
docs/source/zh-cn/basics/plugin.md

docs(plugin.md): fix 'path' declaration example

---

History.md
package.json

Release 2.13.0

---

docs/source/_data/promotion.yml

docs: remove promo logo

---

docs/source/en/basics/service.md
docs/source/zh-cn/basics/service.md

docs: Update service.md

---

index.d.ts
lib/application.js
lib/egg.js
test/lib/egg.test.js

`Application` and `Agent` class
move `createAnonymousContext` method to `EggApplication` class

feat: add create anonymous context to agent

---

index.d.ts
lib/application.js
lib/egg.js
test/lib/egg.test.js

`Application` and `Agent` class
move `createAnonymousContext` method to `EggApplication` class

backport: add create anonymous context to agent

---

History.md
package.json

Release 1.17.0

---

lib/application.js
test/fixtures/apps/app-server-timeout/app.js
test/lib/cluster/app_worker.test.js

- import at https://github.com/eggjs/egg/pull/3133
- discuss to remove it at https://github.com/eggjs/egg/pull/3222
cc @browsnet

fix: remove timeout log msg

---

History.md
package.json

close https://github.com/eggjs/egg/issues/3232

Release 2.14.1

---

docs/source/en/core/httpclient.md
docs/source/zh-cn/core/httpclient.md

fix typo: doc/httpclient

---

docs/source/en/core/cookie-and-session.md
docs/source/zh-cn/core/cookie-and-session.md

> None
* Add Cookie-Session Usage special tip

doc: session special usage tip

---

History.md
docs/source/zh-cn/basics/schedule.md
package.json

Release 2.14.2

---

docs/source/en/tutorials/typescript.md
docs/source/zh-cn/tutorials/typescript.md

Ref: https://github.com/eggjs/egg/pull/3374
---

doc (typescript.md): Sync the English translation

---

CONTRIBUTING.md

Fix typo: "submit an PR" should be "submit a PR"

---

docs/source/en/core/logger.md
docs/source/zh-cn/core/logger.md

- 补充 `logger.disableConsoleAfterReady` 的文档

docs(logger): add logger.disableConsoleAfterReady to docs

---

package.json

- 不指定 egg 依赖的 @types/node 版本的话装的是 8.x 的，似乎会导致 tsc 运行有问题，所以指定一下依赖为最新版本。

fix: fix ts ci

---

History.md
package.json

Release 2.15.0

---

app/extend/context.js
test/app/extend/context.test.js
test/fixtures/apps/context-config-app/app/controller/home.js

feat: allow ctx.router setter

---

History.md
package.json

Release 2.16.0

---

index.d.ts
test/fixtures/apps/app-ts/app/controller/foo.ts

Declaration of `egg-view` has migrated to https://github.com/eggjs/egg-view/blob/master/index.d.ts . And egg has import 'egg-view' in dts, so it's no need to declare again in egg.

feat(types): remove declaration of view

---

History.md
package.json

Release 2.16.1

---

History.md
package.json

Release 2.16.2

---

docs/source/en/tutorials/typescript.md
docs/source/zh-cn/tutorials/typescript.md

docs(typescript): Fix Wrong Path Of LifeCycle Of Tutorial Of TypeScript 

---

lib/egg.js
test/lib/egg.test.js

closes https://github.com/eggjs/egg/issues/3468

fix: createAnonymousContext add host in headers

---

lib/loader/agent_worker_loader.js
test/app/extend/context.test.js
test/lib/egg.test.js

agent
agent context can be extended

feat: agent context can be extended

---

History.md
package.json

Release 2.17.0

---

History.md
package.json

Release 2.18.0

---

History.md
package.json

Release 2.20.0

---

app/extend/request.js
test/app/extend/request.test.js

fix: empty querystring must be cached

---

index.d.ts

add Singleton class declare for this case:https://github.com/eggjs/egg-redis/pull/27
- any feature?

fix: add Singleton class declare typings

---

lib/application.js
lib/core/messenger/local.js
test/app/extend/context.test.js
test/fixtures/apps/app-server-customized-client-error/config/config.default.js
test/lib/cluster/app_worker.test.js
test/lib/core/messenger/local.test.js

fix: onClientError remove content-length header

---

README.md
README.zh-CN.md

https://github.com/eggjs/egg/pull/913/files#diff-3

chore: remove unused plugins.puml link

---

.github/PULL_REQUEST_TEMPLATE.md
docs/source/en/core/development.md
docs/source/en/tutorials/typescript.md
docs/source/zh-cn/core/development.md
docs/source/zh-cn/tutorials/typescript.md

docs: remove egg-ts-helper && inspect-brk

---

lib/application.js
package.json

https://github.com/eggjs/egg-mock/pull/98

feat: expose app.server

---

History.md
package.json

**fetures**
* expose app.server
* [[`9671a354a`](http://github.com/eggjs/egg/commit/9671a354a919cefcab40b7a96208d8d8de5d44ed)] - feat: expose app.server (#3601) (TZ | 天猪 <<atian25@qq.com>>)

Release 1.18.0

---

app/extend/request.js
config/config.default.js
test/app/extend/request.test.js

 feat: support config.maxProxyCount to help get the real client ip

---

History.md
package.json

Release 2.21.0

---

History.md
package.json

Release 1.19.0

---

History.md
package.json

Release 2.21.1

---

index.d.ts
test/fixtures/apps/app-ts-type-check/normal.ts

feat: index.d.ts添加单进程模式

---

docs/source/en/core/httpclient.md
docs/source/zh-cn/core/httpclient.md

docs: fix httpclient proxy

---

lib/loader/app_worker_loader.js
test/doc.test.js
test/fixtures/apps/custom-loader/app.js
test/fixtures/apps/custom-loader/app/controller/user.js
test/fixtures/apps/custom-loader/app/repository/user.js
test/fixtures/apps/custom-loader/app/router.js
test/lib/core/custom_loader.test.js

fix: loadCustomLoader should be run before loadCustomApp

---

History.md
package.json

Release 2.22.0

---

History.md

docs: fix history time

---

History.md
package.json

Release 2.22.1

---

History.md
package.json

https://github.com/eggjs/egg/pull/3660/files
这个改漏了

Release proposal 2.22.1

---

History.md
package.json

Release 2.22.2

---

docs/source/en/core/httpclient.md
docs/source/zh-cn/core/httpclient.md
lib/core/messenger/index.js

https://github.com/node-modules/urllib/pull/322

feat: httpclient upload files

---

docs/source/zh-cn/core/deployment.md

https 相关配置的说明

---

docs/source/en/tutorials/sequelize.md
docs/source/zh-cn/tutorials/sequelize.md

修改了官网中的Sequelize教程[文档](https://eggjs.org/zh-cn/tutorials/sequelize.html#%E7%BC%96%E5%86%99%E4%BB%A3%E7%A0%81)，由于[sequelize(5.0.0)](http://docs.sequelizejs.com/manual/upgrade-to-v5.html)中将findById, findByPrimary函数替换为findByPk函数，故对官网中的示例代码进行修改。

docs: fix sequelize.md

---

docs/source/en/core/deployment.md

start parameters about https

---

index.d.ts
test/fixtures/apps/app-ts-type-check/normal.ts

补充 customLogger 的声明，同时优化一下原有 logger 的声明

fix(typings): add custom logger typings

---

docs/source/en/tutorials/sequelize.md
docs/source/zh-cn/tutorials/sequelize.md

fix: typos

---

docs/source/en/basics/app-start.md
docs/source/zh-cn/basics/app-start.md

add `module.exports = AppBootHook` in sample code.

docs(lifecyle): add class export in sample code

---

docs/source/zh-cn/core/deployment.md

- none
- add alinode supported platforms

docs: add alinode supported platforms

---

config/config.default.js
test/app/middleware/body_parser.test.js

feat: more log for bodyParser

---

History.md

Release 2.23.0

---

docs/source/en/core/logger.md
docs/source/zh-cn/core/logger.md

- close https://github.com/eggjs/egg/issues/3812
- relate https://github.com/eggjs/egg/pull/3815

docs(logger): formatter

---

.github/FUNDING.yml

chore: add sponsor config

---

docs/source/zh-cn/core/deployment.md

none
* add faq related to the node.js performance platform

docs(deployment): add faq related to the node.js performance platform

---

docs/source/en/advanced/cluster-client.md
docs/source/zh-cn/advanced/cluster-client.md

docs: update lf url

---

.github/FUNDING.yml

docs: add opencollective to sponsors list

---

docs/source/en/core/security.md
docs/source/zh-cn/core/security.md

docs(security): hsts is disabled by default

---

docs/source/en/core/deployment.md
docs/source/zh-cn/core/deployment.md

docs(deployment): update the description for hostname

---

.github/workflows/ci.yml
docs/source/_data/promo_link.yml

docs: add promo link

---

.github/workflows/ci.yml
.travis.yml
app/extend/request.js
config/config.default.js
test/app/extend/request.test.js
test/lib/core/httpclient.test.js

feat: support config.maxIpsCount

---

History.md
package.json

Release 1.20.0

---

History.md
package.json

Release 2.25.0

---

index.d.ts

index.d.ts
egg-static的变更type，egg这里没追上

fix: index.d.ts

---

docs/source/en/basics/router.md
docs/source/zh-cn/basics/router.md

typo: 修改错误单词

---

History.md
package.json

Release 2.26.0

---

index.d.ts

feat: add http method patch to typings

---

docs/source/en/basics/plugin.md

docs(plugin): format en/basics/plugin.md

---

docs/source/en/basics/router.md
docs/source/zh-cn/basics/router.md
docs/source/zh-cn/core/security.md

docs: fix typo in router

---

index.d.ts

解决bodyParser type不全和部分文档默认值不对问题

update bodyParser types and doc

---

docs/source/en/tutorials/typescript.md
docs/source/zh-cn/tutorials/typescript.md

…ing unittest generation js code

docs(typescript): Add --noEmit to unittest example code to avoid running unittest generation js code

---

docs/source/en/core/logger.md
docs/source/zh-cn/core/logger.md

Update doc for config of logger.consoleLevel

---

package.json
test/lib/core/dnscache_httpclient.test.js
test/utils.js

test: make dnscache test case more stable

---

.github/workflows/ci.yml
.travis.yml

test: run test on node 14

---

index.d.ts

修复curl方法的类型定义，使其和urllib.httpclient.request保持一致。
当前的类型定义和代码实现不符，使用时会导致给curl传递了泛型之后返回类型有误，以及无法正确标记参数中包含callback时的类型。

fix(dts):fix curl type

---

lib/application.js

How to extend helper。
We support developers to extend Helper through app/extend/helper.js. But on the official website is /app/helper.
close eggjs/egg#4361

docs:update docs about how to extends ctx.helper

---

.travis.yml
index.d.ts
test/fixtures/apps/app-ts/app/controller/foo.ts
test/lib/plugins/i18n.test.js

Logger DTS
export EggLogger type

type: export EggLogger

---

docs/source/en/intro/egg-and-koa.md
docs/source/zh-cn/intro/egg-and-koa.md

docs: update compress url

---

docs/source/en/faq.md

docs
Fixed many grammatical errors as well a couple of spelling
errors in faq.md in english language under en directory.

docs: fix spelling mistakes and grammatical errors

---

index.d.ts

Types are missing in `HttpClientConfig`
Ref: https://github.com/eggjs/egg/blob/master/lib/core/dnscache_httpclient.js#L16

type: Added missing types in HttpClientConfig

---

.travis.yml
app/extend/context.js
test/lib/core/cookies.test.js
test/lib/plugins/i18n.test.js

fix egg 1.x cookie init configuration (egg 2.x had support)

feat: egg 1.x support cookies config init

---

History.md

Release 2.28.0

---

README.md
README.zh-CN.md

docs: update badge to github action

---

docs/source/en/basics/config.md
docs/source/zh-cn/basics/config.md

docs(config): optimize multiple env configuration description

---

package.json
test/fixtures/apps/config-env/.gitignore
test/fixtures/apps/config-env/config/config.default.js
test/fixtures/apps/config-env/config/plugin.js
test/fixtures/apps/config-env/package.json
test/lib/egg.test.js

示例如何覆盖 rundir 和 logger dir
https://github.com/eggjs/egg-core/pull/225

test: showcase for env.EGG_APP_CONFIG

---

docs/source/en/core/security.md
docs/source/zh-cn/core/security.md

Double Cookie Defense should enabled on all kind of request

doc: csrf double cookie defense should enabled on all method

---

lib/egg.js
test/fixtures/apps/dumpconfig/config/plugin.js
test/lib/core/loader/config_loader.test.js
test/lib/egg.test.js

feat: dumpconfig also dump disabled plugin

---

History.md
package.json

Release 2.29.0

---

docs/source/_data/promo_link.yml

docs: d2 ads

---

app/extend/request.js

chore: fix comment typo at request.js

---

index.d.ts
test/fixtures/apps/app-ts/app/controller/foo.ts

fix: fix query typing

---

History.md
package.json

Release 2.29.2

---

index.d.ts
test/fixtures/apps/app-ts/app/middleware/default_ctx.ts
test/fixtures/apps/app-ts/app/middleware/generic_ctx.ts

Refs:
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50249

fix: fix ctx body as any

---

History.md
package.json

Release 2.29.3

---

docs/source/en/core/logger.md

docs: fix allowDebugAtProd configuration parameter values

---

docs/source/en/basics/schedule.md
docs/source/zh-cn/basics/schedule.md

doc: fix schedule reference

---

docs/source/zh-cn/basics/router.md

Typo fixture：制定 -> 指定

---

lib/agent.js

fix: remove internal interval handler when close agent

---

History.md
package.json

Release 2.29.4

---

docs/source/zh-cn/advanced/loaderUpdate.md

docs: fix loaderUpdate.md didReady example

---

docs/source/zh-cn/tutorials/typescript.md

docs: update ts docs

---

docs/source/zh-cn/core/logger.md

For the specification of zh-CN documents, change `,` to `，`
No need to check this.
no
fix typo on doc

doc: Typo fixture:「,」->「，」

---

test/lib/core/singleton.test.js

1. Rename the group names to be more clear.
2. Remove the 'createAsync' to 'async' group at unit test (async test already has it).
3. Format the whole document to be more clear.
4. Make 'create' to '_create' as the inner function to avoid
misunderstanding (the outer function 'create').
---

unittest: rename and remove some duplicated tests

---

History.md
package.json

Release 2.30.0

---

History.md
package.json

Release 2.32.0

---

README.md
README.zh-CN.md

docs: update contributors

---

app/middleware/meta.js
test/app/middleware/meta.test.js
test/fixtures/apps/middlewares-meta-enablePerformanceTimer/app/controller/home.js
test/fixtures/apps/middlewares-meta-enablePerformanceTimer/app/router.js
test/fixtures/apps/middlewares-meta-enablePerformanceTimer/config/config.default.js
test/fixtures/apps/middlewares-meta-enablePerformanceTimer/package.json

feat: meta middleware x-readtime support performanceStarttime

---

README.md
README.zh-CN.md

docs: update node version

---

site/docs/index.md

docs: add english transalations of home

---

app/middleware/site_file.js
config/config.default.js
test/app/middleware/site_file.test.js
test/fixtures/apps/siteFile-custom-cacheControl/app/router.js
test/fixtures/apps/siteFile-custom-cacheControl/config/config.default.js
test/fixtures/apps/siteFile-custom-cacheControl/package.json

feat: siteFile support custom control-cache

---

test/app/middleware/site_file.test.js
test/lib/core/httpclient.test.js

test: change error code assert

---

lib/egg.js
test/lib/egg.test.js

feat: dumpConfig add appInfo

---

History.md
package.json

Release 2.35.0

---

README.md
README.zh-CN.md

**Before:**
[![contributors](https://ergatejs.implements.io/badges/contributors/eggjs/egg.svg)](https://github.com/eggjs/egg/graphs/contributors)
**After:**
[![contributors](https://contrib.rocks/image?repo=eggjs/egg&max=240&columns=26)](https://github.com/eggjs/egg/graphs/contributors)

chore: update README.md

---

.github/ISSUE_TEMPLATE/rfc_cn.md

All links on git.io will stop redirecting after April 29, 2022.
- https://github.blog/changelog/2022-04-25-git-io-deprecation/

chore: remove git.io

---

lib/application.js
lib/core/dnscache_httpclient.js
test/app/extend/request.test.js
test/async/index.test.js
test/bench/server.js
test/lib/application.test.js

Fixture for some English comments in syntax.

chore: typo fixture

---

History.md
package.json

https://github.com/eggjs/egg/pull/4968

Release 2.36.0

---

.github/workflows/nodejs.yml
History.md
package.json
test/lib/core/httpclient.test.js

closes https://github.com/eggjs/egg/issues/4998

Release 3.0.0

---

index.d.ts
test/fixtures/apps/app-ts/config/config.ts

https://github.com/eggjs/egg/pull/5000

🐛 FIX: Add config.httpclient.useHttpClientNext defined

---

History.md
package.json

Release 3.1.0

---

.github/workflows/gh-pages.yml

- update workflow for gh-pages

chore: fix action for gh-pages

---

History.md
package.json

Release 3.3.0

---

lib/application.js
package.json
test/fixtures/apps/app-die-ignore-code/app/router.js
test/fixtures/apps/app-die-ignore-code/config/config.default.js
test/fixtures/apps/app-die-ignore-code/package.json
test/lib/cluster/master.test.js

Co-authored-by: hugh.hyj <hugh.hyj@alibaba-inc.com>
cherry-pick https://github.com/eggjs/egg/pull/5027 into `2.x`
See https://github.com/eggjs/egg/pull/5027

feat(graceful): support serverGracefulIgnoreCode (#5027)

---

package.json

temp fix invalid filename
https://github.com/cojs/busboy/pull/48#issuecomment-1257993976

fix: fallback egg-multipart to v2

---

History.md
package.json

Release 3.3.1

---

History.md
package.json

Release 3.3.2

---

History.md

chore: update history

---

History.md
package.json

Release 3.3.3

---

site/docs/basics/objects.zh-CN.md

see #2673 
文本参考自 https://github.com/eggjs/eggjs.github.io/blob/docs/docs/zh/guide/application.md
TODO: 根据上述 issue 的讨论，「在它上面我们可以挂载一些全局的方法和对象」这句话同样不太合理，是否考虑移除？
btw，好奇 eggjs.github.io 是老版本的文档吗？之前从来没有注意到它

docs: fix Application description

---

.github/workflows/nodejs.yml
package.json

🤖 TEST: Add Node.js 19 ci runner

---

app/middleware/meta.js
package.json
site/docs/core/deployment.md
site/docs/core/deployment.zh-CN.md
site/docs/intro/migration.md
site/docs/intro/migration.zh-CN.md
test/app/middleware/meta.test.js

👌 IMPROVE: Don't need to patch keep-alive header on Node.js >= 14.20.0

---

.eslintrc
config/config.default.js
index.js
lib/egg.js
test/fixtures/apps/dumptiming-slowBootActionMinDuration/app.js
test/fixtures/apps/dumptiming-slowBootActionMinDuration/config/config.default.js
test/fixtures/apps/dumptiming-slowBootActionMinDuration/config/plugin.js
test/fixtures/apps/dumptiming-slowBootActionMinDuration/package.json
test/lib/egg.test.js

👌 IMPROVE: Print warnning log when boot action takes more than 5000ms

---

History.md
package.json

Release 3.4.0

---

lib/egg.js
package.json

不影响
debug模式不检查cluster心跳 isCheckHeartbeat 。 ref: https://github.com/eggjs/egg/issues/5057

feat: debug mode does not check heartbeat

---

lib/egg.js
test/ts/index.test.js

- [] tests and/or benchmarks are included

fix: dump config/timing when timeout

---

.github/workflows/vercel-preview.yml
.github/workflows/vercel-production.yml
.gitignore
vercel.json

use github actions to deploy doc site.

chore: use actions to deploy vercel project

---

index.d.ts
package.json

📦 NEW: Add ctxStorage and currentContext d.ts

---

History.md

Release 3.6.0

---

app/extend/context.js
config/config.default.js
index.d.ts
lib/core/logger.js
package.json
test/fixtures/apps/app-enableFastContextLogger/app/controller/home.js
test/fixtures/apps/app-enableFastContextLogger/app/router.js
test/fixtures/apps/app-enableFastContextLogger/config/config.default.js
test/fixtures/apps/app-enableFastContextLogger/package.json
test/fixtures/apps/tracer-demo/app/controller/foo.js
test/fixtures/apps/tracer-demo/app/router.js
test/lib/core/httpclient_tracer_demo.test.js
test/lib/core/logger.test.js

https://github.com/eggjs/egg-logger/pull/81

📦 NEW: Upgrade egg-logger v3 to enable localStorage

---

History.md
package.json

Release 3.7.0

---

package.json
test/lib/core/logger.test.js

https://github.com/eggjs/egg-schedule/pull/58

👌 IMPROVE: Upgrade egg-schedule to v4

---

History.md
package.json

Release 3.8.0

---

index.d.ts
lib/application.js
test/app/extend/application.test.js
test/fixtures/apps/app-runInAnonymousContextScope/app.js
test/fixtures/apps/app-runInAnonymousContextScope/config/config.default.js
test/fixtures/apps/app-runInAnonymousContextScope/config/config.unittest.js
test/fixtures/apps/app-runInAnonymousContextScope/package.json
test/fixtures/apps/app-ts-type-check/normal.ts

📦 NEW: Run async function in the anonymous context scope

---

index.d.ts
package.json
test/app/middleware/meta.test.js
test/fixtures/apps/app-ts/app/controller/foo.ts
test/fixtures/apps/app-ts/config/config.ts

👌 IMPROVE: Keep more compatible d.ts on httpclient request

---

index.d.ts
test/fixtures/apps/app-ts-type-check/normal.ts

🐛 FIX: Typo on HttpClient request

---

History.md
package.json
test/fixtures/apps/app-ts-type-check/normal.ts

Release 3.9.0

---

.github/workflows/release.yml
index.d.ts
package.json
test/fixtures/apps/app-ts/app/controller/foo.ts

🐛 FIX: Should import types from urllib-next root path

---

.github/workflows/release.yml
package.json

fix: Enable auto npm release workflow

---

.github/workflows/nodejs.yml
.github/workflows/release.yml
package.json
test/fixtures/apps/tracer-demo/app/controller/foo.js
test/lib/cluster/app_worker.test.js
test/lib/core/httpclient_tracer_demo.test.js

test: use artusjs/github-actions to run CI

---

index.d.ts
test/fixtures/apps/app-ts/app/controller/foo.ts

fix: fix currentContext typo

---

index.d.ts
package.json

feat: use egg-core@5

---

app/middleware/site_file.js
test/app/middleware/site_file.test.js
test/fixtures/apps/favicon-function/app/controller/home.js
test/fixtures/apps/favicon-function/app/router.js
test/fixtures/apps/favicon-function/config/config.default.js
test/fixtures/apps/favicon-function/package.json

We could use a function to customize favicon config

feat: siteFile favicon config support function type

---

site/docs/index.md
site/docs/index.zh-CN.md

doc: set promo to recruit

---

package.json
test/lib/cluster/app_worker.test.js
test/lib/core/context_httpclient_timeout.test.js

chore: remove assert-extends

---

.github/workflows/nodejs.yml
index.d.ts
package.json
test/app/extend/request.test.js
test/fixtures/apps/app-ts-type-check/normal.ts

fix https://github.com/cnpm/cnpmcore/pull/370

feat: export urllib types

---

index.d.ts

fix: export urllib types directly

---

index.d.ts
test/fixtures/apps/app-ts/app/controller/foo.ts

add missing pathFor and methods defines

fix(types): app.router.url params should be optional

---

test/lib/core/logger.test.js
test/lib/egg.test.js

1. Remove useless 'empty.txt' in the plugin folder.
2. Combine some promises together as a chain to work with to save time.
3. Remove some useless 'function*()'.

test: improve some unit tests

---

CONTRIBUTING.md
CONTRIBUTING.zh-CN.md
README.md
README.zh-CN.md

1. Typo fixes for "CONTRIBUTING.md" and "README.md" in both English and Chinese versions.
2. Add language switchers for "CONTRIBUTING.md" and "README.md" in both English and Chinese versions.
---

doc: typo fixes and improvements

---

CONTRIBUTING.md
CONTRIBUTING.zh-CN.md

1. Update the Simplified Chinese version for some links.
2. Update the English ones (better syntax).
---

doc: update "CONTRIBUTING.md"

---

lib/core/singleton.js
test/lib/core/singleton.test.js

feat: add getSingletonInstance alias to singleton.get(id)

---

site/docs/index.md
site/docs/index.zh-CN.md

doc: remove expired promo

---

lib/core/messenger/ipc.js
lib/egg.js
lib/loader/app_worker_loader.js

Fix for some comments in the codes.
---

chore: comments fix

---

package.json
test/app/middleware/body_parser.test.js

closes https://github.com/eggjs/egg/issues/5214

fix: compatible with content-type extra semicolon

---

site/docs/advanced/index.md
site/docs/advanced/index.zh-CN.md
site/docs/basics/index.md
site/docs/basics/index.zh-CN.md
site/docs/core/index.md
site/docs/core/index.zh-CN.md

Add all the missing links for the menu items as shortcuts.
---

doc: add missing links for menu items

---

site/docs/tutorials/index.md
site/docs/tutorials/index.zh-CN.md

docs: Official maintained ORM model is egg-orm

---

site/docs/tutorials/mysql.md
site/docs/tutorials/mysql.zh-CN.md

docs: add mysql count use cases

---

index.d.ts

fix: add missing args definition on runSchedule

---

site/docs/index.md

documentation only
fix multiple typos found on the front page

docs: fix multiple typo in front page

---

site/docs/core/error-handling.md

"handers" should be "handlers" in some comments.
Refs: #5243.
----

doc: typo fixtures

---

.github/workflows/pr-contributor-welcome.yml

follow https://github.com/ant-design/ant-design/pull/44184

chore: add pr welcome action

---

site/docs/tutorials/mysql.zh-CN.md

chore: typo fix on mysql example

---

.github/workflows/chainalert.yml
.github/workflows/vercel-preview.yml
.github/workflows/vercel-production.yml

https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

chore: use actions/checkout@v4
